// Colour palette presets and the built-in theme library used by the Studio editor.
import { RISO_NOIR_ID, RISO_NOIR_TOKENS } from "../../features/site/risoNoir";

export const PALETTES = [
  { id: "punk",    label: "Punk Violet",    bg: "#0a0910", text: "#f3f1ee", accent: "#A855F7", swatches: ["#0a0910","#f3f1ee","#A855F7"] },
  { id: "dark",    label: "Midnight Black", bg: "#030213", text: "#ffffff", accent: "#A855F7", swatches: ["#030213","#ffffff","#A855F7"] },
  { id: "light",   label: "Gallery White",  bg: "#f8f7f4", text: "#111111", accent: "#000000", swatches: ["#f8f7f4","#111111","#000000"] },
  { id: "minimal", label: "Pure Minimal",   bg: "#ffffff",  text: "#000000", accent: "#666666", swatches: ["#ffffff","#000000","#888888"] },
  { id: "warm",    label: "Warm Clay",      bg: "#fdf6f0",  text: "#2c1810", accent: "#c96b2e", swatches: ["#fdf6f0","#2c1810","#c96b2e"] },
  { id: "forest",  label: "Deep Forest",    bg: "#0f1e14",  text: "#e8f5e9", accent: "#4caf50", swatches: ["#0f1e14","#e8f5e9","#4caf50"] },
  { id: "ink",     label: "Modern Ink",     bg: "#1a1a1a",  text: "#f5f5f5", accent: "#e74c3c", swatches: ["#1a1a1a","#f5f5f5","#e74c3c"] },
  { id: "royal",   label: "Royal Velvet",   bg: "#1a0b2e", text: "#f3e8ff", accent: "#fbbf24", swatches: ["#1a0b2e","#f3e8ff","#fbbf24"] },
  { id: "sage",    label: "Soft Sage",      bg: "#e7ede6", text: "#1a2e1a", accent: "#4a7c4a", swatches: ["#e7ede6","#1a2e1a","#4a7c4a"] },
  { id: "nord",    label: "Arctic Nord",    bg: "#2e3440", text: "#eceff4", accent: "#88c0d0", swatches: ["#2e3440","#eceff4","#88c0d0"] },
  { id: "cyber",   label: "Night City",     bg: "#000000", text: "#ffffff", accent: "#fde047", swatches: ["#000000","#ffffff","#fde047"] },
  { id: "rose",    label: "Desert Rose",    bg: "#fff5f5", text: "#742a2a", accent: "#f56565", swatches: ["#fff5f5","#742a2a","#f56565"] },
  { id: "ocean",   label: "Deep Ocean",     bg: "#0c1a25", text: "#e2e8f0", accent: "#38bdf8", swatches: ["#0c1a25","#e2e8f0","#38bdf8"] },
];

// Top-level preset keys that "Apply" copies onto the design. Every key applied here (and every
// key in a preset's `global`) must have a Studio › Style control — themeLibrary.test.ts enforces it.
// `palettePreset` is expanded into editable colours; the older fontSize/cornerStyle/
// animationLevel keys are not read by the storefront, so they are not applied.
export const THEME_APPLIED_KEYS = [
  "font", "buttonStyle", "productCardStyle", "productHoverEffect", "imageAspectRatio", "productImageLayout",
  "productContentPosition", "productColumnsDesktop", "productColumnsMobile", "cardRadius", "productCTA",
  "catalogLayoutStyle", "showCatalogControls",
];

export const THEME_LIBRARY = [
  {
    id: RISO_NOIR_ID,
    name: "Lyricalmyrical Riso Noir",
    mood: "Riso Press on black: white ink, flare-red accent, square outlined objects and flat offset shadows",
    palettePreset: "dark",
    font: "Archivo", fontSize: "md", cornerStyle: "sharp", buttonStyle: "solid", animationLevel: "minimal",
    productCardStyle: "editorial", productHoverEffect: "lift", imageAspectRatio: "3:4", productImageLayout: "grid",
    productContentPosition: "right", productColumnsDesktop: 3, productColumnsMobile: 1, cardRadius: 0, productCTA: "ADD TO BAG",
    catalogLayoutStyle: "reference", showCatalogControls: true,
    homeLayoutTemplate: RISO_NOIR_ID,
    global: RISO_NOIR_TOKENS,
  },
  {
    id: "lyricalmyrical-riso",
    name: "Lyricalmyrical Riso (Paper)",
    mood: "Riso Press: flat ink on newsprint, flare-red accent, square outlined objects and offset shadows",
    palettePreset: "warm",
    font: "Archivo", fontSize: "md", cornerStyle: "sharp", buttonStyle: "solid", animationLevel: "minimal",
    productCardStyle: "editorial", productHoverEffect: "lift", imageAspectRatio: "3:4", productImageLayout: "grid",
    productContentPosition: "right", productColumnsDesktop: 3, productColumnsMobile: 1, cardRadius: 0, productCTA: "ADD TO BAG",
    catalogLayoutStyle: "reference", showCatalogControls: true,
    homeLayoutTemplate: "lyricalmyrical-riso",
    global: {
      themeStyle: "riso", backgroundColor: "#faf6ec", textColor: "#100f0d", primaryColor: "#e8402a",
      secondaryColor: "#1b3fe0", surfaceColor: "#f0e9da", surfaceRaisedColor: "#ffffff",
      successColor: "#0a6b47", dangerColor: "#b4271a", warningColor: "#ffc93c",
      favoriteColor: "#e8402a", mutedTextColor: "#5f5950", borderColor: "#100f0d",
      linkColorHover: "#b4271a", overlayColor: "#100f0d", headingFont: "Anton", bodyFont: "Archivo",
      headingWeight: 400, bodyWeight: 400, letterSpacing: "normal", lineHeight: 1.6,
      buttonColor: "#e8402a", buttonTextColor: "#100f0d", buttonHoverBgColor: "#ff6b55", buttonHoverTextColor: "#100f0d",
      buttonRadius: 0, buttonUppercase: true, buttonShadow: false,
      badgeBgPrimary: "#e8402a", badgeTextPrimary: "#100f0d", badgeBgSecondary: "#1b3fe0", badgeTextSecondary: "#ffffff",
      headerBg: "#faf6ec", headerColor: "#100f0d", footerBg: "#100f0d", footerLayout: "4col",
      showAnnouncement: true, announcementBg: "#100f0d", announcementColor: "#faf6ec", announcementScrolling: true,
      announcementFontSize: 11, announcementWeight: 900, announcementTracking: 0.18, announcementSpeed: 28,
      checkoutAccentColor: "#e8402a", checkoutBgColor: "#faf6ec", checkoutInputRadius: 0,
      cartDrawerBg: "#faf6ec", cartDrawerText: "#100f0d", cartDrawerMuted: "#5f5950",
      cartDrawerSurface: "#ffffff", cartDrawerBorder: "#100f0d", pageChromeStyle: "theme",
      navStyle: "default", wordmarkStyle: "two-part",
      wordmarkPrimary: "Lyricalmyrical", wordmarkSecondary: "Books", wordmarkSecondaryMuted: false,
      wordmarkSize: 1.8, wordmarkWeight: 400, showCategoryChips: true, categoryChipShowCounts: true,
      catalogHeading: "Printed matter", productBorderRadius: 0, showCatalogCount: true, showQtyStepper: true, productDescriptionStyle: "designed",
    },
  },
  {
    id: "lyricalmyrical-punk",
    name: "Lyricalmyrical Punk",
    mood: "Violet-on-black editorial punk — serif drama, sticker nav, film grain",
    palettePreset: "punk",
    font: "Inter", fontSize: "md", cornerStyle: "sharp", buttonStyle: "solid", animationLevel: "moderate",
    productCardStyle: "editorial", productHoverEffect: "zoom", imageAspectRatio: "3:4", productImageLayout: "slider",
    productContentPosition: "right", productColumnsDesktop: 3, productColumnsMobile: 1, cardRadius: 2, productCTA: "ADD TO BAG",
    catalogLayoutStyle: "modern", showCatalogControls: true,
    // Installed on request after applying the preset (never silently overwrites sections).
    homeLayoutTemplate: "lyricalmyrical-punk",
    // Applied to the root design AND both page surfaces so every storefront
    // surface (homepage, catalog, product page, cart drawer, footer, custom
    // pages) inherits the full token set. Each key remains individually
    // adjustable afterwards from the Colors / Typography / Navigation panels.
    global: {
      backgroundColor: "#0a0910", textColor: "#f3f1ee", primaryColor: "#A855F7",
      surfaceColor: "#141219", surfaceRaisedColor: "#1c1a22",
      successColor: "#34d399", dangerColor: "#fb7185", warningColor: "#f5b942",
      favoriteColor: "#fb7185", mutedTextColor: "rgba(243,241,238,0.56)",
      borderColor: "rgba(255,255,255,0.12)", linkColorHover: "#A855F7",
      overlayColor: "#0a0910",
      headingFont: "Cormorant Garamond", bodyFont: "Inter", font: "Inter", headingWeight: 600,
      buttonColor: "#A855F7", buttonTextColor: "#ffffff",
      buttonHoverBgColor: "#C084FC", buttonHoverTextColor: "#ffffff",
      buttonStyle: "solid", buttonRadius: 999, buttonUppercase: true,
      badgeBgPrimary: "#A855F7", badgeTextPrimary: "#ffffff",
      badgeBgSecondary: "#1c1a22", badgeTextSecondary: "#f3f1ee",
      headerBg: "#0a0910", headerColor: "#f3f1ee",
      showAnnouncement: true, announcementBg: "#141219", announcementColor: "rgba(243,241,238,0.56)",
      announcementScrolling: true, announcementFontSize: 11, announcementWeight: 600,
      announcementTracking: 0.14, announcementSpeed: 24,
      checkoutAccentColor: "#A855F7",
      cartDrawerBg: "#141219", cartDrawerText: "#f3f1ee", cartDrawerMuted: "rgba(243,241,238,0.56)",
      cartDrawerSurface: "#1c1a22", cartDrawerBorder: "rgba(255,255,255,0.12)",
      footerLayout: "4col", footerBg: "#08070c", pageChromeStyle: "theme",
      navStyle: "stickers", wordmarkStyle: "two-part",
      wordmarkPrimary: "Lyricalmyrical", wordmarkSecondary: "Books",
      wordmarkSecondaryMuted: true, wordmarkSize: 1.75, wordmarkWeight: 600,
      navPillRadius: "14px 4px 14px 4px", navPillRotate: true, navPillActivePalette: true,
      showCategoryChips: true, categoryChipShowCounts: true,
      catalogHeading: "The Archive", showCatalogCount: true,
      showQtyStepper: true, productDescriptionStyle: "designed",
    },
  },
  { id: "lyrical-photo-reference", name: "Lyrical Photo Reference", mood: "Black reference storefront with oversized masthead, ruled nav and three-column book grid", palettePreset: "cyber", font: "Inter", fontSize: "lg", cornerStyle: "sharp", buttonStyle: "outline", animationLevel: "minimal", productCardStyle: "editorial", productHoverEffect: "zoom", imageAspectRatio: "1:1", productImageLayout: "grid", productContentPosition: "right", productColumnsDesktop: 3, productColumnsMobile: 1, cardRadius: 0, productCTA: "VIEW", catalogLayoutStyle: "reference", showCatalogControls: false, global: { catalogMastheadText: "Lyricalmyrical Books", catalogHeaderWidth: 1180, catalogHeaderRuleWidth: 4, catalogGridGap: 18, catalogTitleTransform: "none", catalogImageFit: "cover", showAnnouncement: false, showCollectionMeta: false, referenceCategoryLimit: 1, catalogCartPlacement: "top-right", catalogMastheadDesktop: 58, catalogMastheadMobile: 38, catalogNavGapDesktop: 40, catalogNavGapMobile: 18, catalogImageFocalX: 50, catalogImageFocalY: 50, headerBg: "#000000", headerColor: "#ffffff", borderColor: "#B1B1AA" } },
  { id: "editorial-luxe", name: "Editorial Luxe", mood: "High-contrast serif with generous spacing", palettePreset: "light", font: "Playfair Display", fontSize: "md", cornerStyle: "rounded", buttonStyle: "outline", animationLevel: "minimal", productCardStyle: "editorial", productHoverEffect: "zoom", imageAspectRatio: "3:4", productImageLayout: "grid", productContentPosition: "right", productColumnsDesktop: 3, productColumnsMobile: 1, cardRadius: 12, productCTA: "READ MORE" },
  { id: "night-neon", name: "Night Neon", mood: "Dark cinematic storefront with energetic accents", palettePreset: "cyber", font: "Space Mono", fontSize: "md", cornerStyle: "sharp", buttonStyle: "solid", animationLevel: "high", productCardStyle: "card", productHoverEffect: "lift", imageAspectRatio: "2:3", productImageLayout: "slider", productContentPosition: "left", productColumnsDesktop: 4, productColumnsMobile: 2, cardRadius: 4, productCTA: "BUY NOW" },
  { id: "earthy-studio", name: "Earthy Studio", mood: "Warm lifestyle brand with artisan feel", palettePreset: "warm", font: "Fraunces", fontSize: "md", cornerStyle: "rounded", buttonStyle: "soft", animationLevel: "moderate", productCardStyle: "editorial", productHoverEffect: "zoom", imageAspectRatio: "3:4", productImageLayout: "stacked", productContentPosition: "right", productColumnsDesktop: 3, productColumnsMobile: 2, cardRadius: 14, productCTA: "DISCOVER" },
  { id: "nordic-minimal", name: "Nordic Minimal", mood: "Clean product-first look focused on clarity", palettePreset: "nord", font: "Inter", fontSize: "sm", cornerStyle: "rounded", buttonStyle: "outline", animationLevel: "minimal", productCardStyle: "minimal", productHoverEffect: "none", imageAspectRatio: "1:1", productImageLayout: "grid", productContentPosition: "right", productColumnsDesktop: 5, productColumnsMobile: 2, cardRadius: 6, productCTA: "VIEW" },
  { id: "botanical-boutique", name: "Botanical Boutique", mood: "Soft, premium organic aesthetic", palettePreset: "sage", font: "Cormorant", fontSize: "md", cornerStyle: "pill", buttonStyle: "soft", animationLevel: "moderate", productCardStyle: "card", productHoverEffect: "zoom", imageAspectRatio: "3:4", productImageLayout: "slider", productContentPosition: "right", productColumnsDesktop: 3, productColumnsMobile: 1, cardRadius: 18, productCTA: "ADD TO BAG" },
  { id: "royal-gallery", name: "Royal Gallery", mood: "Rich luxury visual system with dramatic hierarchy", palettePreset: "royal", font: "EB Garamond", fontSize: "lg", cornerStyle: "sharp", buttonStyle: "solid", animationLevel: "high", productCardStyle: "editorial", productHoverEffect: "lift", imageAspectRatio: "2:3", productImageLayout: "stacked", productContentPosition: "left", productColumnsDesktop: 3, productColumnsMobile: 1, cardRadius: 2, productCTA: "ACQUIRE" },
  { id: "modern-atelier", name: "Modern Atelier", mood: "Refined studio layout with sleek modern lines", palettePreset: "minimal", font: "Outfit", fontSize: "md", cornerStyle: "sharp", buttonStyle: "outline", animationLevel: "minimal", productCardStyle: "minimal", productHoverEffect: "lift", imageAspectRatio: "1:1", productImageLayout: "grid", productContentPosition: "right", productColumnsDesktop: 4, productColumnsMobile: 2, cardRadius: 0, productCTA: "EXPLORE" },
  { id: "coastal-breeze", name: "Coastal Breeze", mood: "Airy coastal style with calm blue contrast", palettePreset: "ocean", font: "DM Sans", fontSize: "md", cornerStyle: "rounded", buttonStyle: "soft", animationLevel: "moderate", productCardStyle: "card", productHoverEffect: "zoom", imageAspectRatio: "3:4", productImageLayout: "slider", productContentPosition: "right", productColumnsDesktop: 4, productColumnsMobile: 2, cardRadius: 16, productCTA: "SHOP NOW" },
  { id: "velvet-rose", name: "Velvet Rose", mood: "Romantic boutique identity with warm highlights", palettePreset: "rose", font: "Lora", fontSize: "md", cornerStyle: "pill", buttonStyle: "solid", animationLevel: "moderate", productCardStyle: "editorial", productHoverEffect: "zoom", imageAspectRatio: "2:3", productImageLayout: "stacked", productContentPosition: "left", productColumnsDesktop: 3, productColumnsMobile: 1, cardRadius: 20, productCTA: "FALL IN LOVE" },
  { id: "forest-cabin", name: "Forest Cabin", mood: "Grounded rustic atmosphere with organic tones", palettePreset: "forest", font: "Montserrat", fontSize: "sm", cornerStyle: "rounded", buttonStyle: "outline", animationLevel: "minimal", productCardStyle: "card", productHoverEffect: "none", imageAspectRatio: "3:4", productImageLayout: "grid", productContentPosition: "right", productColumnsDesktop: 4, productColumnsMobile: 2, cardRadius: 10, productCTA: "VIEW DETAILS" },
  { id: "inkline-tech", name: "Inkline Tech", mood: "Minimal tech retail with punchy contrast accents", palettePreset: "ink", font: "Syne", fontSize: "sm", cornerStyle: "sharp", buttonStyle: "solid", animationLevel: "high", productCardStyle: "minimal", productHoverEffect: "lift", imageAspectRatio: "1:1", productImageLayout: "slider", productContentPosition: "left", productColumnsDesktop: 5, productColumnsMobile: 2, cardRadius: 3, productCTA: "ADD" },
  { id: "golden-noir", name: "Golden Noir", mood: "Dark premium experience with luminous CTA focus", palettePreset: "dark", font: "Bebas Neue", fontSize: "lg", cornerStyle: "sharp", buttonStyle: "solid", animationLevel: "high", productCardStyle: "editorial", productHoverEffect: "lift", imageAspectRatio: "2:3", productImageLayout: "stacked", productContentPosition: "left", productColumnsDesktop: 3, productColumnsMobile: 1, cardRadius: 1, productCTA: "ENTER SHOP" },
  { id: "luxe-dark-commerce", name: "Luxe Dark Commerce", mood: "Shopify Horizon-inspired dark aesthetic with editorial serif drama", palettePreset: "dark", font: "Cormorant", fontSize: "lg", cornerStyle: "sharp", buttonStyle: "outline", animationLevel: "moderate", productCardStyle: "editorial", productHoverEffect: "lift", imageAspectRatio: "2:3", productImageLayout: "stacked", productContentPosition: "left", productColumnsDesktop: 3, productColumnsMobile: 1, cardRadius: 0, productCTA: "DISCOVER" },
  { id: "conversion-engine", name: "Conversion Engine", mood: "High-converting DTC storefront optimised for speed and add-to-cart", palettePreset: "light", font: "Inter", fontSize: "md", cornerStyle: "rounded", buttonStyle: "solid", animationLevel: "minimal", productCardStyle: "card", productHoverEffect: "zoom", imageAspectRatio: "1:1", productImageLayout: "grid", productContentPosition: "right", productColumnsDesktop: 4, productColumnsMobile: 2, cardRadius: 8, productCTA: "ADD TO CART" },
  { id: "artisan-market", name: "Artisan Market", mood: "Handmade craft aesthetic with warm tactile energy", palettePreset: "warm", font: "Fraunces", fontSize: "md", cornerStyle: "rounded", buttonStyle: "soft", animationLevel: "moderate", productCardStyle: "card", productHoverEffect: "lift", imageAspectRatio: "3:4", productImageLayout: "grid", productContentPosition: "right", productColumnsDesktop: 3, productColumnsMobile: 2, cardRadius: 4, productCTA: "SHOP HANDMADE" },
  { id: "tech-minimal", name: "Tech Minimal", mood: "Clean SaaS-inspired product store with sharp precision", palettePreset: "minimal", font: "DM Sans", fontSize: "sm", cornerStyle: "sharp", buttonStyle: "solid", animationLevel: "minimal", productCardStyle: "minimal", productHoverEffect: "none", imageAspectRatio: "1:1", productImageLayout: "grid", productContentPosition: "right", productColumnsDesktop: 5, productColumnsMobile: 2, cardRadius: 2, productCTA: "BUY NOW" },
  { id: "coastal-living", name: "Coastal Living", mood: "Airy lifestyle and home goods aesthetic with calm coastal warmth", palettePreset: "nord", font: "Lora", fontSize: "md", cornerStyle: "rounded", buttonStyle: "soft", animationLevel: "moderate", productCardStyle: "editorial", productHoverEffect: "zoom", imageAspectRatio: "3:4", productImageLayout: "slider", productContentPosition: "right", productColumnsDesktop: 3, productColumnsMobile: 1, cardRadius: 12, productCTA: "EXPLORE" },
  { id: "urban-streetwear", name: "Urban Streetwear", mood: "Hypebeast energy with bold display type and high-impact drops", palettePreset: "cyber", font: "Bebas Neue", fontSize: "lg", cornerStyle: "sharp", buttonStyle: "solid", animationLevel: "high", productCardStyle: "card", productHoverEffect: "zoom", imageAspectRatio: "2:3", productImageLayout: "grid", productContentPosition: "left", productColumnsDesktop: 4, productColumnsMobile: 2, cardRadius: 0, productCTA: "COP IT" },
];
