import { test, expect } from "vitest";
import { createRequire } from "node:module";
import { readFileSync } from "node:fs";
import vm from "node:vm";
const require = createRequire(import.meta.url);
const source = readFileSync(new URL("./index.js", import.meta.url), "utf8");
function harness(identity = { email: "lyricalmyricalbooks@gmail.com", email_verified: true }, pending = false) {
  const docs = {
    orders: { A: { paymentStatus: "paid", paymentMethod: "Stripe", stripePaymentIntentId: "pi_saved", total: 60, customerRequest: { type: "return", status: "open" }, items: [{ id: "a", quantity: 2, format: "Paperback" }, { id: "b", quantity: 1, format: "Paperback" }] } },
    books: { a: { status: "published", format: "Paperback", retailPrice: 20, trackInventory: true, stockLevel: 3 }, b: { status: "published", format: "Paperback", retailPrice: 20, trackInventory: true, stockLevel: 3 } },
    "shipping-profiles": { "general-profile": { zones: [{ countries: ["CA"], rates: [{ id: "post", name: "Post", type: "flat", base: 5, additional: 2, enabled: true }] }] } },
    settings: { website: {} }, adminSecrets: { stripe: { secretKey: "sk_live_fake" } },
  };
  const writes = [], refunds = [];
  const db = { collection(name) { return {
    doc(id) { return { path: `${name}/${id}`, async get() { const value = docs[name]?.[id]; return { id, exists: !!value, data: () => value ? structuredClone(value) : undefined }; }, async update(change) { writes.push({ path: `${name}/${id}`, change }); Object.assign(docs[name]?.[id] || {}, change); }, async set(value, options) { docs[name] ||= {}; docs[name][id] = options?.merge ? { ...(docs[name][id] || {}), ...value } : value; } }; },
    async get() { return { docs: Object.entries(docs[name] || {}).map(([id, value]) => ({ id, data: () => structuredClone(value) })) }; }
  }; }, async runTransaction(fn) { const queued = []; const result = await fn({ get: ref => ref.get(), update: (ref, value) => queued.push(() => ref.update(value)), set: (ref, value) => queued.push(() => ref.set(value)) }); for (const apply of queued) await apply(); return result; } };
  const firestore = () => db; firestore.FieldValue = { increment: value => value };
  const admin = { initializeApp() {}, firestore, auth: () => ({ verifyIdToken: async () => identity }) };
  class Stripe { constructor() { this.refunds = { create: async (params, opts) => { refunds.push({ params, opts }); return { id: "re_saved", amount: 6000, currency: "cad", status: pending ? "pending" : "succeeded" }; } }; } }
  const wrap = (...args) => args.at(-1);
  const mockRequire = name => name === "firebase-admin" ? admin : name === "stripe" ? Stripe : name.startsWith("firebase-functions/v2/") ? new Proxy({}, { get: () => wrap }) : name === "firebase-functions/params" ? { defineSecret: () => ({ value: () => "fake" }) } : name === "./rateLimit" ? { ...require(name), hitLimit: async () => true } : require(name);
  const module = { exports: {} };
  vm.runInNewContext(source + "\nmodule.exports.__refund = applyOrderRefund;", { module, exports: module.exports, require: mockRequire, process: { env: { APP_CHECK_MODE: "off" } }, Buffer, console, URL, setTimeout, clearTimeout, AbortController }, { filename: "index.js" });
  const call = async (handler, body, auth = true) => { const response = { code: 200, body: null, set() {}, status(code) { this.code = code; return this; }, json(body) { this.body = body; return this; }, send(body) { this.body = body; return this; } }; await module.exports[handler]({ method: "POST", headers: auth ? { authorization: "Bearer token" } : {}, body: { orderId: "A", ...body } }, response); return response; };
  const approveInspect = async () => { for (const action of ["approved", "received", "inspected"]) expect((await call("manageReturn", { action, instructions: "Return to confirmed address", inspection: [{ index: 0, quantity: 2, condition: "resellable" }, { index: 1, quantity: 1, condition: "damaged" }] })).code).toBe(200); };
  return { docs, writes, refunds, call, approveInspect, complete: module.exports.__refund };
}
test("shipping estimates use current catalog prices and profile weights, ignore spoofed digital/price fields, and never write orders", async () => { const app = harness(); const result = await app.call("cartShippingPreview", { country: "Canada", postalCode: "M6G3H1", items: [{ id: "a", quantity: 2, price: 0, digital: true }] }, false); expect(result.code).toBe(200); expect(result.body.quotes[0].price).toBe(7); expect(result.body.digitalOnly).toBe(false); expect(app.writes).toEqual([]); expect(app.refunds).toEqual([]); });
test("unavailable destinations and drafts never invent shipping quotes", async () => { const app = harness(); const result = await app.call("cartShippingPreview", { country: "France", postalCode: "75001", items: [{ id: "a", quantity: 1 }] }); expect(result.body.quotes).toEqual([]); app.docs.books.a.status = "draft"; expect((await app.call("cartShippingPreview", { country: "Canada", postalCode: "M6G", items: [{ id: "a", quantity: 1 }] })).code).toBe(409); });
test("shipping rejects malformed quantities and unknown destinations", async () => { const app = harness(); expect((await app.call("cartShippingPreview", { country: "Unknown", postalCode: "123", items: [{ id: "a", quantity: 1 }] })).code).toBe(400); expect((await app.call("cartShippingPreview", { country: "Canada", postalCode: "123", items: [{ id: "a", quantity: -1 }] })).code).toBe(409); });
test("return changes require the verified allowlisted admin", async () => { const app = harness(null); expect((await app.call("manageReturn", { action: "approved", instructions: "Return" }, false)).code).toBe(401); expect((await harness({ email: "reader@example.com", email_verified: true }).call("manageReturn", { action: "approved" })).code).toBe(403); expect(app.writes).toEqual([]); });
test("approval does not restock or refund; inspection remains private", async () => { const app = harness(); await app.approveInspect(); expect(app.docs.books.a.stockLevel).toBe(3); expect(app.refunds).toEqual([]); expect(app.docs.orders.A.returnProgress).not.toHaveProperty("inspection"); expect(app.docs["order-operations"].A.returnCase.inspection).toHaveLength(2); });
test("unreceived return cannot be refunded", async () => { const app = harness(); expect((await app.call("manageReturn", { action: "approved", instructions: "Return" })).code).toBe(200); expect((await app.call("refundOrder", {})).code).toBe(409); expect(app.refunds).toEqual([]); });
test("a return request the shop hasn't approved (e.g. an e-book) can be refunded directly", async () => { const app = harness(); app.docs.orders.A.items = [{ id: "a", quantity: 1, format: "E-book (EPUB)" }]; expect((await app.call("manageReturn", { action: "approved", instructions: "Return" })).code).toBe(409); const result = await app.call("refundOrder", {}); expect(result.code).toBe(200); expect(app.docs.orders.A.paymentStatus).toBe("refunded"); });
test("a refund that never reached a provider releases its claim so the return can continue", async () => { const app = harness(); delete app.docs.orders.A.stripePaymentIntentId; expect((await app.call("refundOrder", {})).code).toBe(409); expect(app.docs.orders.A.refundRequest).toBeNull(); expect((await app.call("manageReturn", { action: "approved", instructions: "Return" })).code).toBe(200); });
test("estimates treat format-only e-books and audiobooks as digital and refuse missing editions", async () => { const app = harness(); app.docs.books.a.format = "Audiobook"; const digital = await app.call("cartShippingPreview", { country: "Canada", postalCode: "M5V 1A1", items: [{ id: "a", quantity: 1 }] }); expect(digital.code).toBe(200); expect(digital.body.digitalOnly).toBe(true); expect((await app.call("cartShippingPreview", { country: "Canada", postalCode: "M5V 1A1", items: [{ id: "b", variantId: "gone", quantity: 1 }] })).code).toBe(409); });
test("verified refund restocks only eligible lines and duplicate refunds do not restock twice", async () => { const app = harness(); await app.approveInspect(); const result = await app.call("refundOrder", { restock: true }); expect(result.code).toBe(200); expect(app.docs.books.a.stockLevel).toBe(5); expect(app.docs.books.b.stockLevel).toBe(3); expect(app.docs.orders.A.returnProgress.state).toBe("completed"); expect(app.refunds[0].opts.idempotencyKey).toBe("order-refund-A-full"); expect((await app.call("refundOrder", {})).code).toBe(409); expect(app.docs.books.a.stockLevel).toBe(5); });
test("pending provider refunds complete without repeating inventory changes", async () => { const app = harness(undefined, true); await app.approveInspect(); expect((await app.call("refundOrder", {})).code).toBe(200); expect(app.docs.orders.A.returnProgress.state).toBe("refund_pending"); expect(app.docs.books.a.stockLevel).toBe(5); await app.complete("A", { provider: "stripe", status: "succeeded", restock: true }); expect(app.docs.orders.A.returnProgress.state).toBe("completed"); expect(app.docs.books.a.stockLevel).toBe(5); });

test("manual returns record a publisher-authorized external refund and selective restock", async () => { const app = harness(); delete app.docs.orders.A.stripePaymentIntentId; app.docs.orders.A.paymentMethod = "e-Transfer"; await app.approveInspect(); expect((await app.call("refundOrder", {})).code).toBe(200); expect(app.docs.orders.A.paymentStatus).toBe("refunded"); expect(app.docs.books.a.stockLevel).toBe(5); expect(app.refunds).toEqual([]); });
test("repeated receipt requests do not change private history or stock", async () => { const app = harness(); await app.call("manageReturn", { action: "approved", instructions: "Return" }); await app.call("manageReturn", { action: "received" }); const before = JSON.stringify(app.docs["order-operations"].A); await app.call("manageReturn", { action: "received" }); expect(JSON.stringify(app.docs["order-operations"].A)).toBe(before); expect(app.docs.books.a.stockLevel).toBe(3); });
