// GENERATED from src/app/features/site/shippingZones.ts (COUNTRIES) — keep in sync;
// shippingGeo.parity.test.ts fails if the two tables differ.
// Server-side geography so zones match by country code, country name or continent.

// [ISO code, name, continent]
const COUNTRIES = [
  ["DZ", "Algeria", "Africa"],
  ["AO", "Angola", "Africa"],
  ["BJ", "Benin", "Africa"],
  ["BW", "Botswana", "Africa"],
  ["BF", "Burkina Faso", "Africa"],
  ["BI", "Burundi", "Africa"],
  ["CV", "Cabo Verde", "Africa"],
  ["CM", "Cameroon", "Africa"],
  ["CF", "Central African Republic", "Africa"],
  ["TD", "Chad", "Africa"],
  ["KM", "Comoros", "Africa"],
  ["CG", "Congo", "Africa"],
  ["CD", "DR Congo", "Africa"],
  ["CI", "Côte d'Ivoire", "Africa"],
  ["DJ", "Djibouti", "Africa"],
  ["EG", "Egypt", "Africa"],
  ["GQ", "Equatorial Guinea", "Africa"],
  ["ER", "Eritrea", "Africa"],
  ["SZ", "Eswatini", "Africa"],
  ["ET", "Ethiopia", "Africa"],
  ["GA", "Gabon", "Africa"],
  ["GM", "Gambia", "Africa"],
  ["GH", "Ghana", "Africa"],
  ["GN", "Guinea", "Africa"],
  ["GW", "Guinea-Bissau", "Africa"],
  ["KE", "Kenya", "Africa"],
  ["LS", "Lesotho", "Africa"],
  ["LR", "Liberia", "Africa"],
  ["LY", "Libya", "Africa"],
  ["MG", "Madagascar", "Africa"],
  ["MW", "Malawi", "Africa"],
  ["ML", "Mali", "Africa"],
  ["MR", "Mauritania", "Africa"],
  ["MU", "Mauritius", "Africa"],
  ["MA", "Morocco", "Africa"],
  ["MZ", "Mozambique", "Africa"],
  ["NA", "Namibia", "Africa"],
  ["NE", "Niger", "Africa"],
  ["NG", "Nigeria", "Africa"],
  ["RW", "Rwanda", "Africa"],
  ["ST", "São Tomé and Príncipe", "Africa"],
  ["SN", "Senegal", "Africa"],
  ["SC", "Seychelles", "Africa"],
  ["SL", "Sierra Leone", "Africa"],
  ["SO", "Somalia", "Africa"],
  ["ZA", "South Africa", "Africa"],
  ["SS", "South Sudan", "Africa"],
  ["SD", "Sudan", "Africa"],
  ["TZ", "Tanzania", "Africa"],
  ["TG", "Togo", "Africa"],
  ["TN", "Tunisia", "Africa"],
  ["UG", "Uganda", "Africa"],
  ["ZM", "Zambia", "Africa"],
  ["ZW", "Zimbabwe", "Africa"],
  ["YT", "Mayotte", "Africa"],
  ["RE", "Réunion", "Africa"],
  ["SH", "Saint Helena", "Africa"],
  ["EH", "Western Sahara", "Africa"],
  ["AQ", "Antarctica", "Antarctica"],
  ["BV", "Bouvet Island", "Antarctica"],
  ["TF", "French Southern Territories", "Antarctica"],
  ["HM", "Heard Island and McDonald Islands", "Antarctica"],
  ["GS", "South Georgia and the South Sandwich Islands", "Antarctica"],
  ["AF", "Afghanistan", "Asia"],
  ["AM", "Armenia", "Asia"],
  ["AZ", "Azerbaijan", "Asia"],
  ["BH", "Bahrain", "Asia"],
  ["BD", "Bangladesh", "Asia"],
  ["BT", "Bhutan", "Asia"],
  ["BN", "Brunei", "Asia"],
  ["KH", "Cambodia", "Asia"],
  ["CN", "China", "Asia"],
  ["CY", "Cyprus", "Asia"],
  ["GE", "Georgia", "Asia"],
  ["HK", "Hong Kong", "Asia"],
  ["IN", "India", "Asia"],
  ["ID", "Indonesia", "Asia"],
  ["IR", "Iran", "Asia"],
  ["IQ", "Iraq", "Asia"],
  ["IL", "Israel", "Asia"],
  ["JP", "Japan", "Asia"],
  ["JO", "Jordan", "Asia"],
  ["KZ", "Kazakhstan", "Asia"],
  ["KW", "Kuwait", "Asia"],
  ["KG", "Kyrgyzstan", "Asia"],
  ["LA", "Laos", "Asia"],
  ["LB", "Lebanon", "Asia"],
  ["MO", "Macao", "Asia"],
  ["MY", "Malaysia", "Asia"],
  ["MV", "Maldives", "Asia"],
  ["MN", "Mongolia", "Asia"],
  ["MM", "Myanmar", "Asia"],
  ["NP", "Nepal", "Asia"],
  ["KP", "North Korea", "Asia"],
  ["OM", "Oman", "Asia"],
  ["PK", "Pakistan", "Asia"],
  ["PS", "Palestine", "Asia"],
  ["PH", "Philippines", "Asia"],
  ["QA", "Qatar", "Asia"],
  ["SA", "Saudi Arabia", "Asia"],
  ["SG", "Singapore", "Asia"],
  ["KR", "South Korea", "Asia"],
  ["LK", "Sri Lanka", "Asia"],
  ["SY", "Syria", "Asia"],
  ["TW", "Taiwan", "Asia"],
  ["TJ", "Tajikistan", "Asia"],
  ["TH", "Thailand", "Asia"],
  ["TL", "Timor-Leste", "Asia"],
  ["TR", "Türkiye", "Asia"],
  ["TM", "Turkmenistan", "Asia"],
  ["AE", "United Arab Emirates", "Asia"],
  ["UZ", "Uzbekistan", "Asia"],
  ["VN", "Vietnam", "Asia"],
  ["YE", "Yemen", "Asia"],
  ["IO", "British Indian Ocean Territory", "Asia"],
  ["AL", "Albania", "Europe"],
  ["AD", "Andorra", "Europe"],
  ["AT", "Austria", "Europe"],
  ["BY", "Belarus", "Europe"],
  ["BE", "Belgium", "Europe"],
  ["BA", "Bosnia and Herzegovina", "Europe"],
  ["BG", "Bulgaria", "Europe"],
  ["HR", "Croatia", "Europe"],
  ["CZ", "Czechia", "Europe"],
  ["DK", "Denmark", "Europe"],
  ["EE", "Estonia", "Europe"],
  ["FI", "Finland", "Europe"],
  ["FR", "France", "Europe"],
  ["DE", "Germany", "Europe"],
  ["GR", "Greece", "Europe"],
  ["HU", "Hungary", "Europe"],
  ["IS", "Iceland", "Europe"],
  ["IE", "Ireland", "Europe"],
  ["IT", "Italy", "Europe"],
  ["LV", "Latvia", "Europe"],
  ["LI", "Liechtenstein", "Europe"],
  ["LT", "Lithuania", "Europe"],
  ["LU", "Luxembourg", "Europe"],
  ["MT", "Malta", "Europe"],
  ["MD", "Moldova", "Europe"],
  ["MC", "Monaco", "Europe"],
  ["ME", "Montenegro", "Europe"],
  ["NL", "Netherlands", "Europe"],
  ["MK", "North Macedonia", "Europe"],
  ["NO", "Norway", "Europe"],
  ["PL", "Poland", "Europe"],
  ["PT", "Portugal", "Europe"],
  ["RO", "Romania", "Europe"],
  ["RU", "Russia", "Europe"],
  ["SM", "San Marino", "Europe"],
  ["RS", "Serbia", "Europe"],
  ["SK", "Slovakia", "Europe"],
  ["SI", "Slovenia", "Europe"],
  ["ES", "Spain", "Europe"],
  ["SE", "Sweden", "Europe"],
  ["CH", "Switzerland", "Europe"],
  ["UA", "Ukraine", "Europe"],
  ["GB", "United Kingdom", "Europe"],
  ["VA", "Vatican City", "Europe"],
  ["AX", "Åland Islands", "Europe"],
  ["FO", "Faroe Islands", "Europe"],
  ["GG", "Guernsey", "Europe"],
  ["GI", "Gibraltar", "Europe"],
  ["IM", "Isle of Man", "Europe"],
  ["JE", "Jersey", "Europe"],
  ["SJ", "Svalbard and Jan Mayen", "Europe"],
  ["AG", "Antigua and Barbuda", "North America"],
  ["BS", "Bahamas", "North America"],
  ["BB", "Barbados", "North America"],
  ["BZ", "Belize", "North America"],
  ["BM", "Bermuda", "North America"],
  ["CA", "Canada", "North America"],
  ["CR", "Costa Rica", "North America"],
  ["CU", "Cuba", "North America"],
  ["DM", "Dominica", "North America"],
  ["DO", "Dominican Republic", "North America"],
  ["SV", "El Salvador", "North America"],
  ["GL", "Greenland", "North America"],
  ["GD", "Grenada", "North America"],
  ["GT", "Guatemala", "North America"],
  ["HT", "Haiti", "North America"],
  ["HN", "Honduras", "North America"],
  ["JM", "Jamaica", "North America"],
  ["MX", "Mexico", "North America"],
  ["NI", "Nicaragua", "North America"],
  ["PA", "Panama", "North America"],
  ["PR", "Puerto Rico", "North America"],
  ["KN", "Saint Kitts and Nevis", "North America"],
  ["LC", "Saint Lucia", "North America"],
  ["VC", "Saint Vincent and the Grenadines", "North America"],
  ["TT", "Trinidad and Tobago", "North America"],
  ["US", "United States", "North America"],
  ["AI", "Anguilla", "North America"],
  ["AW", "Aruba", "North America"],
  ["BL", "Saint Barthélemy", "North America"],
  ["BQ", "Bonaire, Sint Eustatius and Saba", "North America"],
  ["KY", "Cayman Islands", "North America"],
  ["CW", "Curaçao", "North America"],
  ["GP", "Guadeloupe", "North America"],
  ["MQ", "Martinique", "North America"],
  ["MS", "Montserrat", "North America"],
  ["MF", "Saint Martin", "North America"],
  ["PM", "Saint Pierre and Miquelon", "North America"],
  ["SX", "Sint Maarten", "North America"],
  ["TC", "Turks and Caicos Islands", "North America"],
  ["VG", "British Virgin Islands", "North America"],
  ["VI", "U.S. Virgin Islands", "North America"],
  ["AR", "Argentina", "South America"],
  ["BO", "Bolivia", "South America"],
  ["BR", "Brazil", "South America"],
  ["CL", "Chile", "South America"],
  ["CO", "Colombia", "South America"],
  ["EC", "Ecuador", "South America"],
  ["GY", "Guyana", "South America"],
  ["PY", "Paraguay", "South America"],
  ["PE", "Peru", "South America"],
  ["SR", "Suriname", "South America"],
  ["UY", "Uruguay", "South America"],
  ["VE", "Venezuela", "South America"],
  ["FK", "Falkland Islands", "South America"],
  ["GF", "French Guiana", "South America"],
  ["AU", "Australia", "Oceania"],
  ["FJ", "Fiji", "Oceania"],
  ["KI", "Kiribati", "Oceania"],
  ["MH", "Marshall Islands", "Oceania"],
  ["FM", "Micronesia", "Oceania"],
  ["NR", "Nauru", "Oceania"],
  ["NZ", "New Zealand", "Oceania"],
  ["PW", "Palau", "Oceania"],
  ["PG", "Papua New Guinea", "Oceania"],
  ["WS", "Samoa", "Oceania"],
  ["SB", "Solomon Islands", "Oceania"],
  ["TO", "Tonga", "Oceania"],
  ["TV", "Tuvalu", "Oceania"],
  ["VU", "Vanuatu", "Oceania"],
  ["AS", "American Samoa", "Oceania"],
  ["CX", "Christmas Island", "Oceania"],
  ["CC", "Cocos (Keeling) Islands", "Oceania"],
  ["CK", "Cook Islands", "Oceania"],
  ["PF", "French Polynesia", "Oceania"],
  ["GU", "Guam", "Oceania"],
  ["NC", "New Caledonia", "Oceania"],
  ["NU", "Niue", "Oceania"],
  ["NF", "Norfolk Island", "Oceania"],
  ["MP", "Northern Mariana Islands", "Oceania"],
  ["PN", "Pitcairn", "Oceania"],
  ["TK", "Tokelau", "Oceania"],
  ["UM", "U.S. Outlying Islands", "Oceania"],
  ["WF", "Wallis and Futuna", "Oceania"],
];

const BY_KEY = new Map();
for (const [code, name, continent] of COUNTRIES) {
  const entry = { code, name, continent };
  BY_KEY.set(code.toLowerCase(), entry);
  BY_KEY.set(name.toLowerCase(), entry);
}
const ALIASES = { US: ["usa", "u.s.", "u.s.a.", "america", "united states of america"], GB: ["uk", "great britain", "england"] };
for (const [code, names] of Object.entries(ALIASES)) {
  const entry = BY_KEY.get(code.toLowerCase());
  if (entry) names.forEach(n => BY_KEY.set(n, entry));
}

const REST_OF_WORLD_NAMES = /^(international|everywhere else|rest of world|worldwide|global|anywhere)$/i;

// "CA", "ca", "Canada", "usa"… -> { code, name, continent } or null.
function resolveCountry(nameOrCode) {
  const q = String(nameOrCode || "").trim().toLowerCase();
  return (q && BY_KEY.get(q)) || null;
}

function isCatchAll(zone) {
  return zone.restOfWorld === true || REST_OF_WORLD_NAMES.test(String(zone.region || "").trim());
}

// A zone's country list may hold ISO codes (current editor) or names (older
// saves); compare by resolved code so both match.
function zoneHasCountry(zone, code) {
  return (zone.countries || []).some(entry => resolveCountry(entry)?.code === code);
}

// Pick the most specific zone for a country: explicit country > continent >
// legacy region-name match > catch-all/rest-of-world.
function matchShippingZone(nameOrCode, zones) {
  if (!zones || zones.length === 0) return null;
  const country = resolveCountry(nameOrCode);
  if (country) {
    const byCountry = zones.find(z => zoneHasCountry(z, country.code));
    if (byCountry) return byCountry;
    const byContinent = zones.find(z => (z.continents || []).includes(country.continent));
    if (byContinent) return byContinent;
    const byLegacy = zones.find(z => {
      const r = String(z.region || "").trim().toLowerCase();
      return r === country.name.toLowerCase() || r === country.continent.toLowerCase();
    });
    if (byLegacy) return byLegacy;
  }
  return zones.find(isCatchAll) || null;
}

module.exports = { COUNTRIES, resolveCountry, matchShippingZone, isCatchAll };
