// AUTO-DERIVED from src/app/features/site/shippingZones.ts — keep in sync.
// Server-side geography so calculateShipping can match zones by country and
// continent (not just exact free-text region names).

// Lowercased country name (+ common aliases) -> [ISO code, continent]
const COUNTRY_BY_NAME = {
  'algeria': ["DZ", 'Africa'],
  'angola': ["AO", 'Africa'],
  'benin': ["BJ", 'Africa'],
  'botswana': ["BW", 'Africa'],
  'burkina faso': ["BF", 'Africa'],
  'burundi': ["BI", 'Africa'],
  'cabo verde': ["CV", 'Africa'],
  'cameroon': ["CM", 'Africa'],
  'central african republic': ["CF", 'Africa'],
  'chad': ["TD", 'Africa'],
  'comoros': ["KM", 'Africa'],
  'congo': ["CG", 'Africa'],
  'dr congo': ["CD", 'Africa'],
  "côte d'ivoire": ["CI", 'Africa'],
  'djibouti': ["DJ", 'Africa'],
  'egypt': ["EG", 'Africa'],
  'equatorial guinea': ["GQ", 'Africa'],
  'eritrea': ["ER", 'Africa'],
  'eswatini': ["SZ", 'Africa'],
  'ethiopia': ["ET", 'Africa'],
  'gabon': ["GA", 'Africa'],
  'gambia': ["GM", 'Africa'],
  'ghana': ["GH", 'Africa'],
  'guinea': ["GN", 'Africa'],
  'guinea-bissau': ["GW", 'Africa'],
  'kenya': ["KE", 'Africa'],
  'lesotho': ["LS", 'Africa'],
  'liberia': ["LR", 'Africa'],
  'libya': ["LY", 'Africa'],
  'madagascar': ["MG", 'Africa'],
  'malawi': ["MW", 'Africa'],
  'mali': ["ML", 'Africa'],
  'mauritania': ["MR", 'Africa'],
  'mauritius': ["MU", 'Africa'],
  'morocco': ["MA", 'Africa'],
  'mozambique': ["MZ", 'Africa'],
  'namibia': ["NA", 'Africa'],
  'niger': ["NE", 'Africa'],
  'nigeria': ["NG", 'Africa'],
  'rwanda': ["RW", 'Africa'],
  'são tomé and príncipe': ["ST", 'Africa'],
  'senegal': ["SN", 'Africa'],
  'seychelles': ["SC", 'Africa'],
  'sierra leone': ["SL", 'Africa'],
  'somalia': ["SO", 'Africa'],
  'south africa': ["ZA", 'Africa'],
  'south sudan': ["SS", 'Africa'],
  'sudan': ["SD", 'Africa'],
  'tanzania': ["TZ", 'Africa'],
  'togo': ["TG", 'Africa'],
  'tunisia': ["TN", 'Africa'],
  'uganda': ["UG", 'Africa'],
  'zambia': ["ZM", 'Africa'],
  'zimbabwe': ["ZW", 'Africa'],
  'afghanistan': ["AF", 'Asia'],
  'armenia': ["AM", 'Asia'],
  'azerbaijan': ["AZ", 'Asia'],
  'bahrain': ["BH", 'Asia'],
  'bangladesh': ["BD", 'Asia'],
  'bhutan': ["BT", 'Asia'],
  'brunei': ["BN", 'Asia'],
  'cambodia': ["KH", 'Asia'],
  'china': ["CN", 'Asia'],
  'cyprus': ["CY", 'Asia'],
  'georgia': ["GE", 'Asia'],
  'hong kong': ["HK", 'Asia'],
  'india': ["IN", 'Asia'],
  'indonesia': ["ID", 'Asia'],
  'iran': ["IR", 'Asia'],
  'iraq': ["IQ", 'Asia'],
  'israel': ["IL", 'Asia'],
  'japan': ["JP", 'Asia'],
  'jordan': ["JO", 'Asia'],
  'kazakhstan': ["KZ", 'Asia'],
  'kuwait': ["KW", 'Asia'],
  'kyrgyzstan': ["KG", 'Asia'],
  'laos': ["LA", 'Asia'],
  'lebanon': ["LB", 'Asia'],
  'macao': ["MO", 'Asia'],
  'malaysia': ["MY", 'Asia'],
  'maldives': ["MV", 'Asia'],
  'mongolia': ["MN", 'Asia'],
  'myanmar': ["MM", 'Asia'],
  'nepal': ["NP", 'Asia'],
  'north korea': ["KP", 'Asia'],
  'oman': ["OM", 'Asia'],
  'pakistan': ["PK", 'Asia'],
  'palestine': ["PS", 'Asia'],
  'philippines': ["PH", 'Asia'],
  'qatar': ["QA", 'Asia'],
  'saudi arabia': ["SA", 'Asia'],
  'singapore': ["SG", 'Asia'],
  'south korea': ["KR", 'Asia'],
  'sri lanka': ["LK", 'Asia'],
  'syria': ["SY", 'Asia'],
  'taiwan': ["TW", 'Asia'],
  'tajikistan': ["TJ", 'Asia'],
  'thailand': ["TH", 'Asia'],
  'timor-leste': ["TL", 'Asia'],
  'türkiye': ["TR", 'Asia'],
  'turkmenistan': ["TM", 'Asia'],
  'united arab emirates': ["AE", 'Asia'],
  'uzbekistan': ["UZ", 'Asia'],
  'vietnam': ["VN", 'Asia'],
  'yemen': ["YE", 'Asia'],
  'albania': ["AL", 'Europe'],
  'andorra': ["AD", 'Europe'],
  'austria': ["AT", 'Europe'],
  'belarus': ["BY", 'Europe'],
  'belgium': ["BE", 'Europe'],
  'bosnia and herzegovina': ["BA", 'Europe'],
  'bulgaria': ["BG", 'Europe'],
  'croatia': ["HR", 'Europe'],
  'czechia': ["CZ", 'Europe'],
  'denmark': ["DK", 'Europe'],
  'estonia': ["EE", 'Europe'],
  'finland': ["FI", 'Europe'],
  'france': ["FR", 'Europe'],
  'germany': ["DE", 'Europe'],
  'greece': ["GR", 'Europe'],
  'hungary': ["HU", 'Europe'],
  'iceland': ["IS", 'Europe'],
  'ireland': ["IE", 'Europe'],
  'italy': ["IT", 'Europe'],
  'latvia': ["LV", 'Europe'],
  'liechtenstein': ["LI", 'Europe'],
  'lithuania': ["LT", 'Europe'],
  'luxembourg': ["LU", 'Europe'],
  'malta': ["MT", 'Europe'],
  'moldova': ["MD", 'Europe'],
  'monaco': ["MC", 'Europe'],
  'montenegro': ["ME", 'Europe'],
  'netherlands': ["NL", 'Europe'],
  'north macedonia': ["MK", 'Europe'],
  'norway': ["NO", 'Europe'],
  'poland': ["PL", 'Europe'],
  'portugal': ["PT", 'Europe'],
  'romania': ["RO", 'Europe'],
  'russia': ["RU", 'Europe'],
  'san marino': ["SM", 'Europe'],
  'serbia': ["RS", 'Europe'],
  'slovakia': ["SK", 'Europe'],
  'slovenia': ["SI", 'Europe'],
  'spain': ["ES", 'Europe'],
  'sweden': ["SE", 'Europe'],
  'switzerland': ["CH", 'Europe'],
  'ukraine': ["UA", 'Europe'],
  'united kingdom': ["GB", 'Europe'],
  'vatican city': ["VA", 'Europe'],
  'antigua and barbuda': ["AG", 'North America'],
  'bahamas': ["BS", 'North America'],
  'barbados': ["BB", 'North America'],
  'belize': ["BZ", 'North America'],
  'bermuda': ["BM", 'North America'],
  'canada': ["CA", 'North America'],
  'costa rica': ["CR", 'North America'],
  'cuba': ["CU", 'North America'],
  'dominica': ["DM", 'North America'],
  'dominican republic': ["DO", 'North America'],
  'el salvador': ["SV", 'North America'],
  'greenland': ["GL", 'North America'],
  'grenada': ["GD", 'North America'],
  'guatemala': ["GT", 'North America'],
  'haiti': ["HT", 'North America'],
  'honduras': ["HN", 'North America'],
  'jamaica': ["JM", 'North America'],
  'mexico': ["MX", 'North America'],
  'nicaragua': ["NI", 'North America'],
  'panama': ["PA", 'North America'],
  'puerto rico': ["PR", 'North America'],
  'saint kitts and nevis': ["KN", 'North America'],
  'saint lucia': ["LC", 'North America'],
  'saint vincent and the grenadines': ["VC", 'North America'],
  'trinidad and tobago': ["TT", 'North America'],
  'united states': ["US", 'North America'],
  'argentina': ["AR", 'South America'],
  'bolivia': ["BO", 'South America'],
  'brazil': ["BR", 'South America'],
  'chile': ["CL", 'South America'],
  'colombia': ["CO", 'South America'],
  'ecuador': ["EC", 'South America'],
  'guyana': ["GY", 'South America'],
  'paraguay': ["PY", 'South America'],
  'peru': ["PE", 'South America'],
  'suriname': ["SR", 'South America'],
  'uruguay': ["UY", 'South America'],
  'venezuela': ["VE", 'South America'],
  'australia': ["AU", 'Oceania'],
  'fiji': ["FJ", 'Oceania'],
  'kiribati': ["KI", 'Oceania'],
  'marshall islands': ["MH", 'Oceania'],
  'micronesia': ["FM", 'Oceania'],
  'nauru': ["NR", 'Oceania'],
  'new zealand': ["NZ", 'Oceania'],
  'palau': ["PW", 'Oceania'],
  'papua new guinea': ["PG", 'Oceania'],
  'samoa': ["WS", 'Oceania'],
  'solomon islands': ["SB", 'Oceania'],
  'tonga': ["TO", 'Oceania'],
  'tuvalu': ["TV", 'Oceania'],
  'vanuatu': ["VU", 'Oceania'],
  "usa": ["US", "North America"],
  "u.s.a.": ["US", "North America"],
  "u.s.": ["US", "North America"],
  "america": ["US", "North America"],
  "united states of america": ["US", "North America"],
  "uk": ["GB", "Europe"],
  "great britain": ["GB", "Europe"],
  "england": ["GB", "Europe"]
};

// ISO code -> continent
const CONTINENT_BY_CODE = {
  "DZ": 'Africa',
  "AO": 'Africa',
  "BJ": 'Africa',
  "BW": 'Africa',
  "BF": 'Africa',
  "BI": 'Africa',
  "CV": 'Africa',
  "CM": 'Africa',
  "CF": 'Africa',
  "TD": 'Africa',
  "KM": 'Africa',
  "CG": 'Africa',
  "CD": 'Africa',
  "CI": 'Africa',
  "DJ": 'Africa',
  "EG": 'Africa',
  "GQ": 'Africa',
  "ER": 'Africa',
  "SZ": 'Africa',
  "ET": 'Africa',
  "GA": 'Africa',
  "GM": 'Africa',
  "GH": 'Africa',
  "GN": 'Africa',
  "GW": 'Africa',
  "KE": 'Africa',
  "LS": 'Africa',
  "LR": 'Africa',
  "LY": 'Africa',
  "MG": 'Africa',
  "MW": 'Africa',
  "ML": 'Africa',
  "MR": 'Africa',
  "MU": 'Africa',
  "MA": 'Africa',
  "MZ": 'Africa',
  "NA": 'Africa',
  "NE": 'Africa',
  "NG": 'Africa',
  "RW": 'Africa',
  "ST": 'Africa',
  "SN": 'Africa',
  "SC": 'Africa',
  "SL": 'Africa',
  "SO": 'Africa',
  "ZA": 'Africa',
  "SS": 'Africa',
  "SD": 'Africa',
  "TZ": 'Africa',
  "TG": 'Africa',
  "TN": 'Africa',
  "UG": 'Africa',
  "ZM": 'Africa',
  "ZW": 'Africa',
  "AF": 'Asia',
  "AM": 'Asia',
  "AZ": 'Asia',
  "BH": 'Asia',
  "BD": 'Asia',
  "BT": 'Asia',
  "BN": 'Asia',
  "KH": 'Asia',
  "CN": 'Asia',
  "CY": 'Asia',
  "GE": 'Asia',
  "HK": 'Asia',
  "IN": 'Asia',
  "ID": 'Asia',
  "IR": 'Asia',
  "IQ": 'Asia',
  "IL": 'Asia',
  "JP": 'Asia',
  "JO": 'Asia',
  "KZ": 'Asia',
  "KW": 'Asia',
  "KG": 'Asia',
  "LA": 'Asia',
  "LB": 'Asia',
  "MO": 'Asia',
  "MY": 'Asia',
  "MV": 'Asia',
  "MN": 'Asia',
  "MM": 'Asia',
  "NP": 'Asia',
  "KP": 'Asia',
  "OM": 'Asia',
  "PK": 'Asia',
  "PS": 'Asia',
  "PH": 'Asia',
  "QA": 'Asia',
  "SA": 'Asia',
  "SG": 'Asia',
  "KR": 'Asia',
  "LK": 'Asia',
  "SY": 'Asia',
  "TW": 'Asia',
  "TJ": 'Asia',
  "TH": 'Asia',
  "TL": 'Asia',
  "TR": 'Asia',
  "TM": 'Asia',
  "AE": 'Asia',
  "UZ": 'Asia',
  "VN": 'Asia',
  "YE": 'Asia',
  "AL": 'Europe',
  "AD": 'Europe',
  "AT": 'Europe',
  "BY": 'Europe',
  "BE": 'Europe',
  "BA": 'Europe',
  "BG": 'Europe',
  "HR": 'Europe',
  "CZ": 'Europe',
  "DK": 'Europe',
  "EE": 'Europe',
  "FI": 'Europe',
  "FR": 'Europe',
  "DE": 'Europe',
  "GR": 'Europe',
  "HU": 'Europe',
  "IS": 'Europe',
  "IE": 'Europe',
  "IT": 'Europe',
  "LV": 'Europe',
  "LI": 'Europe',
  "LT": 'Europe',
  "LU": 'Europe',
  "MT": 'Europe',
  "MD": 'Europe',
  "MC": 'Europe',
  "ME": 'Europe',
  "NL": 'Europe',
  "MK": 'Europe',
  "NO": 'Europe',
  "PL": 'Europe',
  "PT": 'Europe',
  "RO": 'Europe',
  "RU": 'Europe',
  "SM": 'Europe',
  "RS": 'Europe',
  "SK": 'Europe',
  "SI": 'Europe',
  "ES": 'Europe',
  "SE": 'Europe',
  "CH": 'Europe',
  "UA": 'Europe',
  "GB": 'Europe',
  "VA": 'Europe',
  "AG": 'North America',
  "BS": 'North America',
  "BB": 'North America',
  "BZ": 'North America',
  "BM": 'North America',
  "CA": 'North America',
  "CR": 'North America',
  "CU": 'North America',
  "DM": 'North America',
  "DO": 'North America',
  "SV": 'North America',
  "GL": 'North America',
  "GD": 'North America',
  "GT": 'North America',
  "HT": 'North America',
  "HN": 'North America',
  "JM": 'North America',
  "MX": 'North America',
  "NI": 'North America',
  "PA": 'North America',
  "PR": 'North America',
  "KN": 'North America',
  "LC": 'North America',
  "VC": 'North America',
  "TT": 'North America',
  "US": 'North America',
  "AR": 'South America',
  "BO": 'South America',
  "BR": 'South America',
  "CL": 'South America',
  "CO": 'South America',
  "EC": 'South America',
  "GY": 'South America',
  "PY": 'South America',
  "PE": 'South America',
  "SR": 'South America',
  "UY": 'South America',
  "VE": 'South America',
  "AU": 'Oceania',
  "FJ": 'Oceania',
  "KI": 'Oceania',
  "MH": 'Oceania',
  "FM": 'Oceania',
  "NR": 'Oceania',
  "NZ": 'Oceania',
  "PW": 'Oceania',
  "PG": 'Oceania',
  "WS": 'Oceania',
  "SB": 'Oceania',
  "TO": 'Oceania',
  "TV": 'Oceania',
  "VU": 'Oceania'
};

const REST_OF_WORLD_NAMES = /^(international|everywhere else|rest of world|worldwide|global|anywhere)$/i;

function resolveCountry(nameOrCode) {
  const q = String(nameOrCode || "").trim().toLowerCase();
  if (!q) return null;
  if (COUNTRY_BY_NAME[q]) return { code: COUNTRY_BY_NAME[q][0], continent: COUNTRY_BY_NAME[q][1] };
  const up = q.toUpperCase();
  if (CONTINENT_BY_CODE[up]) return { code: up, continent: CONTINENT_BY_CODE[up] };
  return null;
}

function isCatchAll(zone) {
  return zone.restOfWorld === true || REST_OF_WORLD_NAMES.test(String(zone.region || "").trim());
}

// Pick the most specific zone for a country: explicit country > continent >
// legacy region-name match > catch-all/rest-of-world.
function matchShippingZone(nameOrCode, zones) {
  if (!zones || zones.length === 0) return null;
  const country = resolveCountry(nameOrCode);
  if (country) {
    const byCountry = zones.find(z => (z.countries || []).includes(country.code));
    if (byCountry) return byCountry;
    const byContinent = zones.find(z => (z.continents || []).includes(country.continent));
    if (byContinent) return byContinent;
    const byLegacy = zones.find(z => {
      const r = String(z.region || "").trim().toLowerCase();
      return r === String(nameOrCode || "").trim().toLowerCase() || r === country.continent.toLowerCase();
    });
    if (byLegacy) return byLegacy;
  }
  return zones.find(isCatchAll) || null;
}

module.exports = { resolveCountry, matchShippingZone, isCatchAll };
