import type { Book, SiteSettings } from "./types";

export const DEFAULT_IMAGE =
  "https://images.unsplash.com/photo-1516979187457-637abb4f9353?crop=entropy&cs=tinysrgb&fit=max&fm=jpg";

export const CATEGORIES = ["All", "Books"] as const;

export const DEFAULT_BOOKS: Book[] = [
  {
    id: "un-fantastico-altrove",
    title: "Un Fantastico Altrove",
    subtitle: "Silvia Clo Di Gregorio",
    description: "A photography book unfolding like a visual diary: analog images, tenderness, distance, and transformation gathered into a quiet artist edition.",
    retailPrice: 40,
    stockLevel: 18,
    format: "Photography book",
    status: "published",
    isFeatured: true,
    photos: [{ url: "https://images.unsplash.com/photo-1512820790803-83ca734da794?crop=entropy&cs=tinysrgb&fit=max&fm=jpg", altText: "Stack of art books" }],
    categories: ["All", "Books"],
    slug: "un-fantastico-altrove",
  },
  {
    id: "oltre-il-tempo",
    title: "Oltre il Tempo",
    subtitle: "Isabella Tortola",
    description: "An image-led meditation on memory, atmosphere, and duration, designed for readers who collect intimate contemporary photography.",
    retailPrice: 27,
    stockLevel: 24,
    format: "Photography book",
    status: "published",
    isFeatured: true,
    photos: [{ url: "https://images.unsplash.com/photo-1521587760476-6c12a4b040da?crop=entropy&cs=tinysrgb&fit=max&fm=jpg", altText: "Bookshelves in an art library" }],
    categories: ["All", "Books"],
    slug: "oltre-il-tempo",
  },
  {
    id: "content-unaware",
    title: "Content Unaware",
    subtitle: "Domenico Pendino",
    description: "A compact artist publication about attention, absence, and mediated images.",
    retailPrice: 20,
    stockLevel: 0,
    format: "Artist book",
    status: "published",
    isFeatured: true,
    photos: [{ url: "https://images.unsplash.com/photo-1495446815901-a7297e633e8d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg", altText: "Open books on a table" }],
    categories: ["All", "Books"],
    slug: "content-unaware",
  },
  {
    id: "cream-show",
    title: "Cream Show",
    subtitle: "Anthea Lasis",
    description: "Raw, intimate documentary work shaped around a distinct Canadian rite of passage.",
    retailPrice: 20,
    stockLevel: 15,
    format: "Photography book",
    status: "published",
    isFeatured: true,
    photos: [{ url: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg", altText: "Paperback book pages" }],
    categories: ["All", "Books"],
    slug: "cream-show",
  },
  {
    id: "collective-photobook",
    title: "Collective Photobook",
    subtitle: "Open Call Edition",
    description: "A forthcoming collective photobook bringing together selected contemporary photography projects.",
    retailPrice: 0,
    stockLevel: 0,
    format: "Coming soon",
    status: "published",
    isFeatured: false,
    photos: [{ url: "https://images.unsplash.com/photo-1519682337058-a94d519337bc?crop=entropy&cs=tinysrgb&fit=max&fm=jpg", altText: "Art books and paper" }],
    categories: ["All", "Books"],
    slug: "collective-photobook",
  },
];

export const DEFAULT_SETTINGS: SiteSettings = {
  announcements: [
    { message: "OPEN CALL · Collective photobook submissions accepted through February 28, 2026" },
  ],
  info: {
    name: "Lyricalmyrical Books",
    description:
      "An independent publishing house based in Toronto with roots in Italy, specializing in photography and contemporary art books.",
    website: "https://www.lyricalmyricalbooks.com/",
  },
  localization: { timezone: "America/Toronto", currency: "EUR" },
  design: {
    primaryColor: "#111111",
    font: "Inter",
    logoText: "Lyricalmyrical Books",
    logoHeight: 24,
    logoPosition: "left",
    categories: CATEGORIES,
    backgroundColor: "#fbfaf7",
    textColor: "#151515",
    headerBg: "#fbfaf7",
    headerColor: "#151515",
    buttonColor: "#151515",
    buttonTextColor: "#fbfaf7",
    buttonStyle: "solid",
    buttonRadius: 0,
    cardRadius: 0,
    imageAspectRatio: "3:4",
    productColumnsDesktop: 4,
    productColumnsMobile: 2,
    containerWidth: 1180,
    sectionSpacing: 56,
    showAnnouncement: true,
    announcementText: "OPEN CALL · Submit your work to lyricalmyricalbooks@gmail.com · Deadline February 28, 2026",
    announcementBg: "#f0eee8",
    announcementColor: "#151515",
    productCTA: "Quick view",
    soldOutLabel: "Sold out",
    showCollectionMeta: true,
    cartLabel: "Cart",
    navHeading: "About",
    heroCTA: "Shop books",
    heroSubtext: "Independent photography and art books from Toronto and Italy.",
    headerLinks: {
      showEnterArchive: true,
      showInformation: true,
      showCustomPages: true,
      showBag: true,
      showSys: false,
    },
    copy: {
      footerAbout:
        "Independent publishing house based in Toronto with roots in Italy, dedicated to photography, contemporary art, artist books, and cross-cultural dialogue.",
      newsletterHeading: "Follow the press",
      newsletterText: "New releases, open calls, and art book announcements from Lyricalmyrical Books.",
      newsletterButton: "Subscribe",
      cartTitle: "Cart",
      cartEmpty: "Your cart is empty.",
      footerLocation: "Toronto · Rome",
    },
    hero: {
      enabled: true,
      height: "fullscreen",
      align: "center",
      overlayOpacity: 0.22,
      autoRotate: false,
      slides: [
        {
          id: "lyricalmyrical-home",
          imageUrl: "https://images.unsplash.com/photo-1516979187457-637abb4f9353?crop=entropy&cs=tinysrgb&fit=max&fm=jpg",
          title: "Lyricalmyrical Books",
          subtitle: "Independent photography and art books",
          ctaText: "Shop books",
          ctaLink: "/shop",
        },
      ],
    },
  },
};

export const SITE_CACHE_KEY = "site-bootstrap-v1";
