// ─────────────────────────────────────────────────────────────────────────────
// Store copy — single source of truth for shopper-facing text.
//
// Every editable string lives here with a sensible default. The storefront reads
// values via getCopy(design, key); the theme editor's "Content & Text" panel
// auto-generates its inputs from COPY_SCHEMA, so adding a new editable string is
// a one-line change in this file (plus a getCopy() call at the render site).
// Values are stored on `design.copy[key]`; missing values use the default.
// An explicitly empty value stays empty so owners can clear optional copy.
// ─────────────────────────────────────────────────────────────────────────────

export type CopyField = {
  key: string;
  label: string;
  default: string;
  multiline?: boolean;
  /** Hint shown under the field, e.g. available tokens. */
  hint?: string;
};

export type CopyGroup = {
  group: string;
  fields: CopyField[];
};

export const COPY_SCHEMA: CopyGroup[] = [
  {
    group: "Site & sharing",
    fields: [
      { key: "siteName", label: "Site name", default: "Lyricalmyrical Books", hint: "Used as {name} in the browser-tab title, share previews and search results." },
      { key: "siteDefaultTitle", label: "Home page title (browser tab / Google)", default: "{name} — Independent Publishing House", hint: "Use {name} for the site name." },
      { key: "siteDefaultDescription", label: "Default description (Google / social previews)", default: "{name} is an independent publishing house based in Toronto, specializing in photography and art books.", multiline: true, hint: "Use {name} for the site name." },
      { key: "siteTitleFormat", label: "Other pages' tab title", default: "{title} — {name}", hint: "Use {title} for the page title and {name} for the site name." },
      { key: "seoArchiveTitle", label: "Catalog page title", default: "Archive" },
      { key: "seoWishlistTitle", label: "Wishlist page title", default: "Your Wishlist" },
      { key: "seoWishlistDescription", label: "Wishlist page description", default: "Books you've saved for later from {name}.", hint: "Use {name} for the site name." },
      { key: "seoCheckoutTitle", label: "Checkout page title", default: "Checkout" },
      { key: "seoCheckoutDescription", label: "Checkout page description", default: "Secure checkout for {name}.", hint: "Use {name} for the site name." },
      { key: "seoAccountTitle", label: "Account page title", default: "Your Account" },
      { key: "seoAccountDescription", label: "Account page description", default: "Manage your account, orders and saved addresses." },
      { key: "seoBookDescription", label: "Book page description (when a book has none)", default: "{title} — {name}", hint: "Use {title} for the book title and {name} for the site name." },
      { key: "seoCollectionTitle", label: "Collection page title", default: "{category} Collection", hint: "Use {category} for the collection name." },
      { key: "seoCollectionDescription", label: "Collection page description", default: "Browse the {category} collection from {name}.", hint: "Use {category} (lower-case) and {name}." },
    ],
  },
  {
    group: "Cart",
    fields: [
      { key: "cartTitle", label: "Cart heading", default: "Shopping Bag" },
      { key: "cartEmpty", label: "Empty cart message", default: "The archive is empty." },
      { key: "cartTotalLabel", label: "Total label", default: "Estimated total" },
      { key: "cartCheckoutButton", label: "Checkout button", default: "PROCEED TO CHECKOUT" },
      {
        key: "cartDeliveryNote",
        label: "Delivery note",
        default: "Estimated delivery 5–7 business days · Taxes calculated at checkout",
        multiline: true,
      },
      { key: "cartCountLabel", label: "Item count line", default: "{count} in your bag", hint: "Use {count} for the number of copies in the bag." },
      { key: "cartCloseAria", label: "Close button — screen-reader label", default: "Close cart" },
      { key: "cartFreeShipAway", label: "Free-shipping progress", default: "{amount} away from free shipping", hint: "Use {amount} for the remaining price." },
      { key: "cartFreeShipQualified", label: "Free-shipping reached", default: "You qualify for free shipping" },
      { key: "cartContinue", label: "Continue-shopping button", default: "Continue shopping" },
      { key: "cartUpsellHeading", label: "Upsell heading", default: "Complete your collection" },
      { key: "cartUpsellAdd", label: "Upsell add button", default: "+ Add to Bag" },
      { key: "cartEachLabel", label: "Price per copy", default: "{price} each", hint: "Use {price} for the price of one copy." },
      { key: "cartRemoveLabel", label: "Remove button", default: "Remove" },
      { key: "cartSubtotalLabel", label: "Subtotal label", default: "Subtotal" },
      { key: "cartShippingLabel", label: "Shipping label", default: "Shipping" },
      { key: "cartShippingValue", label: "Shipping value", default: "Calculated at checkout" },
      { key: "cartOnlyAvailable", label: "Stock-limit warning", default: "Only {count} available", hint: "Use {count} for the stock left." },
      { key: "trustSecureLabel", label: "Trust badge 1", default: "Secure" },
      { key: "trustTrackedLabel", label: "Trust badge 2", default: "Tracked" },
      { key: "trustReturnsLabel", label: "Trust badge 3", default: "Returns" },
      { key: "cartQtyAria", label: "Quantity group — screen-reader label", default: "Quantity for {title}", hint: "Use {title} for the book title." },
      { key: "cartDecreaseAria", label: "Decrease — screen-reader label", default: "Decrease quantity of {title}", hint: "Use {title} for the book title." },
      { key: "cartIncreaseAria", label: "Increase — screen-reader label", default: "Increase quantity of {title}", hint: "Use {title} for the book title." },
      { key: "cartRemoveAria", label: "Remove — screen-reader label", default: "Remove {title} from cart", hint: "Use {title} for the book title." },
    ],
  },
  {
    group: "Newsletter",
    fields: [
      { key: "newsletterHeading", label: "Heading", default: "Join the Archive" },
      {
        key: "newsletterText",
        label: "Description",
        default: "New publications, limited editions, and press announcements — delivered quietly.",
        multiline: true,
      },
      { key: "newsletterPlaceholder", label: "Email placeholder", default: "your@email.com" },
      { key: "newsletterLoading", label: "Newsletter subscribing label", default: "..." },
      { key: "newsletterButton", label: "Button label", default: "JOIN" },
      { key: "newsletterSuccess", label: "Success message", default: "✓ You're on the list." },
      { key: "newsletterError", label: "Error message", default: "Something went wrong. Try again." },
    ],
  },
  {
    group: "Footer",
    fields: [
      {
        key: "footerAbout",
        label: "About blurb",
        default:
          "An independent publishing house based in Toronto, specializing in contemporary photography and art books.",
        multiline: true,
      },
      { key: "footerNavHeading", label: "Navigation heading", default: "Navigate" },
      { key: "footerWordmark", label: "Footer wordmark (single-line style)", default: "LYRICALMYRICAL BOOKS" },
      { key: "footerLinkShop", label: "Link: Shop", default: "Shop" },
      { key: "footerLinkTrack", label: "Link: Track order", default: "Track Order" },
      { key: "footerLinkInstagram", label: "Link: Instagram", default: "Instagram" },
      { key: "footerLinkContact", label: "Link: Contact", default: "Contact" },
      { key: "footerLegalHeading", label: "Legal heading", default: "Legal" },
      { key: "policyTitleShipping", label: "Policy link & page title: Shipping", default: "Shipping Policy" },
      { key: "policyTitleReturns", label: "Policy link & page title: Returns", default: "Returns Policy" },
      { key: "policyTitlePrivacy", label: "Policy link & page title: Privacy", default: "Privacy Policy" },
      { key: "policyTitleTerms", label: "Policy link & page title: Terms", default: "Terms of Service" },
      { key: "footerLocationHeading", label: "Location heading (4-column footer)", default: "Location" },
      { key: "footerLocation", label: "Location line", default: "Toronto, Canada" },
      {
        key: "footerCopyright",
        label: "Copyright line",
        default: "© {year} Lyricalmyrical Books · All rights reserved",
        hint: "Use {year} for the current year.",
      },
    ],
  },
  {
    group: "Product page",
    fields: [
      { key: "pdpCrumbShop", label: "Breadcrumb: first link", default: "Shop" },
      { key: "pdpBreadcrumbAria", label: "Breadcrumb — screen-reader label", default: "Breadcrumb" },
      { key: "pdpCaption", label: "Photo caption", default: "Fig. {n}", hint: "Use {n} for the photo number." },
      { key: "pdpCaptionCount", label: "Photo caption counter", default: "{n} of {total}", hint: "Use {n} for the photo number and {total} for how many photos." },
      { key: "pdpInStock", label: "Stock line (plenty left)", default: "In stock" },
      { key: "pdpBackorder", label: "Stock line (backorder)", default: "Out of stock · ships when restocked", hint: "Shown when a book is sold out but set to keep selling (Books › Inventory › Allow backorders)." },
      { key: "pdpInStockCount", label: "Stock line (few left)", default: "In stock · {count} left", hint: "Shown at or below the “only N left” threshold. Use {count} for the number left." },
      { key: "pdpPhotosAria", label: "Thumbnails — screen-reader label", default: "Photos" },
      { key: "pdpDetailsAria", label: "Details tabs — screen-reader label", default: "Product information" },
      { key: "ariaGoToPhoto", label: "Thumbnail / dot — screen-reader label", default: "Go to photo {n}", hint: "Use {n} for the photo number." },
      { key: "relatedHeading", label: "Related products heading", default: "From the Archive" },
      { key: "backToCatalog", label: "Back link label", default: "Back" },
      { key: "addToBagLabel", label: "Add to bag button", default: "ADD TO BAG" },
      { key: "bookLoading", label: "Loading text", default: "Loading" },
      { key: "bookPhotoAlt", label: "Product photo — alt text", default: "{title} — view {n}", hint: "Use {title} for the book title and {n} for the photo number." },
      { key: "bookNotFound", label: "Not-found message", default: "Publication not found" },
      { key: "bookReturn", label: "Not-found button", default: "Return to Archive" },
      { key: "bookFormatLabel", label: "Format selector label", default: "Format / Edition" },
      { key: "bookAdded", label: "Added-to-bag confirmation", default: "Added to Bag" },
      { key: "bookShare", label: "Share button — label", default: "Share" },
      { key: "alertHeading", label: "Back-in-stock: heading", default: "Notify me when it's back" },
      { key: "alertPlaceholder", label: "Back-in-stock: email placeholder", default: "your@email.com" },
      { key: "alertButton", label: "Back-in-stock: button", default: "NOTIFY ME" },
      { key: "alertSuccess", label: "Back-in-stock: success message", default: "✓ We'll email you as soon as it's available." },
      { key: "alertError", label: "Back-in-stock: error message", default: "Please enter a valid email and try again." },
      { key: "bookLinkCopied", label: "Share: link copied message", default: "Link copied to clipboard" },
      { key: "onlyLeft", label: "Low-stock badge", default: "Only {count} left", hint: "Use {count} for the number left." },
      { key: "saveAmount", label: "Sale savings badge", default: "Save {amount}", hint: "Use {amount} for the saving." },
      { key: "tabDescription", label: "Accordion: Description", default: "Description" },
      { key: "tabDetails", label: "Tab: Details", default: "Details" },
      { key: "tabSpecs", label: "Accordion: Specifications", default: "Specifications" },
      { key: "tabReviews", label: "Accordion: Reviews", default: "Reviews" },
      { key: "bundleHeading", label: "Bundle heading", default: "Frequently Bought Together" },
      { key: "ariaPrevPhoto", label: "Previous photo — screen-reader label", default: "Previous photo" },
      { key: "ariaNextPhoto", label: "Next photo — screen-reader label", default: "Next photo" },
      { key: "ariaQtyDown", label: "Decrease quantity — screen-reader label", default: "Decrease quantity" },
      { key: "ariaQtyUp", label: "Increase quantity — screen-reader label", default: "Increase quantity" },
      { key: "productDescriptionLabel", label: "Designed description eyebrow", default: "ABOUT THIS EDITION" },
      { key: "specFormat", label: "Spec: format", default: "Format" },
      { key: "specLanguage", label: "Spec: language", default: "Language" },
      { key: "specDimensions", label: "Spec: dimensions", default: "Dimensions" },
      { key: "specIsbn", label: "Spec: ISBN", default: "ISBN" },
      { key: "specWeight", label: "Spec: weight", default: "Weight" },
      { key: "specAvailability", label: "Spec: availability", default: "Availability" },
      { key: "specRemaining", label: "Spec: stock left", default: "{count} remaining", hint: "Use {count} for the number left." },
      { key: "priceOnRequest", label: "Price missing text", default: "Price on request" },
      { key: "noDescription", label: "No-description text", default: "No description available." },
      { key: "bundleTotal", label: "Bundle total label", default: "Total:" },
      { key: "bundleAdd", label: "Bundle add button", default: "Add Both to Bag" },
      { key: "bundleAdding", label: "Bundle add button (adding)", default: "Adding Both..." },
      { key: "wishlistSaveTitle", label: "Heart tooltip (not saved)", default: "Save to wishlist" },
      { key: "wishlistInTitle", label: "Heart tooltip (saved)", default: "In wishlist" },
      { key: "categoryFallback", label: "Category label when a book has none", default: "Publication" },
    ],
  },
  {
    group: "Catalog & empty states",
    fields: [
      { key: "catalogEmpty", label: "No results message", default: "No publications match these filters." },
      { key: "catalogAllCategories", label: "All-categories chip", default: "ALL" },
      { key: "catalogCountOne", label: "Title count (1)", default: "{count} title", hint: "Use {count} for the number." },
      { key: "catalogCountMany", label: "Title count (many)", default: "{count} titles", hint: "Use {count} for the number." },
    ],
  },
  {
    group: "Custom pages & 404",
    fields: [
      { key: "pageLoading", label: "Page loading text", default: "Loading…" },
      { key: "pageEyebrow", label: "Page eyebrow", default: "Page" },
      { key: "errorTitle", label: "Crash screen message", default: "Something went wrong" },
      { key: "errorReload", label: "Crash screen button", default: "Reload" },
      { key: "pageHomeLink", label: "Header 'home' link", default: "HOME" },
      {
        key: "historyBody",
        label: "History of LM — body",
        default: "Lyricalmyrical Books is an independent publishing house based in Toronto, with roots in Italy. We specialize in photography and art books, bringing artists, images, and ideas together through carefully made printed editions.",
        multiline: true,
      },
      {
        key: "historySubtext",
        label: "History of LM — text underneath",
        default: "Independent publishing between Toronto and Italy — photography, art, and books made to last.",
        multiline: true,
      },
      { key: "notFoundCode", label: "404 number", default: "404" },
      { key: "notFoundTitle", label: "404 message", default: "Page not found" },
      { key: "notFoundBack", label: "404 back link", default: "BACK TO HOME" },
    ],
  },
  {
    group: "Loading screen",
    fields: [
      { key: "loadingAria", label: "Accessible label", default: "Loading Lyricalmyrical Books" },
      { key: "loadingTag", label: "Sticker tag", default: "Toronto · Est. independently" },
      { key: "loadingWordmarkA", label: "Wordmark (first part)", default: "Lyrical" },
      { key: "loadingWordmarkB", label: "Wordmark (accent part)", default: "myrical" },
      { key: "loadingSub", label: "Subline", default: "Books / printed matter" },
      { key: "loadingStatus", label: "Status text", default: "Pulling the first print" },
    ],
  },
  {
    group: "Under construction",
    fields: [
      { key: "ucAria", label: "Accessible label", default: "Site under construction" },
      { key: "ucTag", label: "Sticker tag", default: "Press is running" },
      { key: "ucHeading", label: "Heading (first part)", default: "Under" },
      { key: "ucHeadingAccent", label: "Heading (accent part)", default: "construction." },
      {
        key: "ucBody", label: "Description", multiline: true,
        default: "We're inking the plates and pulling fresh proofs. The shop will be back shortly — thanks for your patience.",
      },
      { key: "ucEmail", label: "Contact email (leave empty to hide the button)", default: "" },
      { key: "ucButton", label: "Contact button", default: "Get in touch" },
      { key: "ucAdmin", label: "Admin button", default: "Admin" },
      { key: "ucFootnote", label: "Footnote", default: "Lyricalmyrical Books — printed matter" },
    ],
  },
  {
    group: "Cookie banner",
    fields: [
      { key: "cookieAria", label: "Accessible label", default: "Cookie consent" },
      { key: "cookieTag", label: "Sticker tag", default: "Your privacy" },
      { key: "cookieHeading", label: "Heading (first part)", default: "Cookies," },
      { key: "cookieHeadingAccent", label: "Heading (accent part)", default: "your call." },
      {
        key: "cookieBody", label: "Description", multiline: true,
        default: "We use cookies to keep the site running, measure traffic, and improve your experience. You can choose which categories to allow.",
      },
      { key: "cookieNecessary", label: "Necessary — label", default: "Necessary" },
      { key: "cookieNecessaryText", label: "Necessary — description", default: "required for the cart and checkout to work." },
      { key: "cookieAnalytics", label: "Analytics — label", default: "Analytics" },
      { key: "cookieAnalyticsText", label: "Analytics — description", default: "anonymous usage statistics so we can improve the site." },
      { key: "cookieMarketing", label: "Marketing — label", default: "Marketing" },
      { key: "cookieMarketingText", label: "Marketing — description", default: "personalized content and abandoned-cart reminders." },
      { key: "cookieAcceptAll", label: "Accept button", default: "Accept all" },
      { key: "cookieReject", label: "Reject button", default: "Reject" },
      { key: "cookieSave", label: "Save button", default: "Save choices" },
      { key: "cookieCustomize", label: "Customize link", default: "Customize" },
    ],
  },
  {
    group: "Maintenance page",
    fields: [
      { key: "maintenanceTag", label: "Sticker tag", default: "Back soon" },
      { key: "maintenanceTitle", label: "Heading", default: "Under maintenance" },
      { key: "maintenanceMessage", label: "Default message (if none set in Settings)", default: "We are updating our archive. Please check back soon.", multiline: true },
      { key: "maintenanceFooter", label: "Footer line", default: "Lyricalmyrical Books · Toronto" },
      { key: "maintenanceAdmin", label: "Admin link label", default: "Admin console" },
    ],
  },
  {
    group: "Header",
    fields: [
      { key: "catalogLoadError", label: "Catalog load error", default: "The catalog could not be loaded. Please try again." },
      { key: "navMenu", label: "Mobile menu", default: "Menu" },
      { key: "navSearch", label: "Nav: Search", default: "Search" },
      { key: "navAdmin", label: "Nav: Admin (debug only)", default: "Admin" },
      { key: "navDropdownAll", label: "Category drop-down: “All” link", default: "All" },
      { key: "ariaMainNavigation", label: "Main navigation — screen-reader label", default: "Main navigation" },
      { key: "ariaSearch", label: "Search icon — screen-reader label", default: "Search" },
      { key: "ariaWishlist", label: "Wishlist icon — screen-reader label", default: "Wishlist" },
      { key: "ariaAccount", label: "Account icon — screen-reader label", default: "Account" },
      { key: "ariaCart", label: "Cart icon — screen-reader label", default: "Open cart" },
      { key: "cartLabel", label: "Cart button label (product page header)", default: "Bag" },
      { key: "currencyLabel", label: "Currency selector label", default: "CURRENCY" },
      { key: "ariaCurrency", label: "Currency selector — screen-reader label", default: "Select currency" },
      { key: "ariaThemeToggle", label: "Light/dark toggle — screen-reader label", default: "Toggle theme" },
      { key: "logoAlt", label: "Logo image — alt text / screen-reader label", default: "Lyricalmyrical Books logo" },
      { key: "ariaPrevSlide", label: "Previous slide — screen-reader label", default: "Previous slide" },
      { key: "ariaNextSlide", label: "Next slide — screen-reader label", default: "Next slide" },
      { key: "poweredBy", label: "Powered-by line", default: "Powered by Lyricalmyrical" },
    ],
  },
  {
    group: "Collection & wishlist pages",
    fields: [
      { key: "collectionBack", label: "Collection: back link", default: "Archive" },
      { key: "collectionEyebrow", label: "Collection: header label", default: "Collection" },
      { key: "breadcrumbAria", label: "Breadcrumb — screen-reader label", default: "Breadcrumb" },
      { key: "breadcrumbHome", label: "Breadcrumb: Home", default: "Home" },
      { key: "breadcrumbCollections", label: "Breadcrumb: Collections", default: "Collections" },
      { key: "wishlistTitle", label: "Wishlist title", default: "Wishlist" },
      { key: "wishlistCount", label: "Wishlist item count", default: "{count} items", hint: "Use {count} for the number of items." },
      { key: "wishlistEmpty", label: "Wishlist empty message", default: "Your wishlist is empty" },
      { key: "wishlistBrowse", label: "Wishlist empty button", default: "Browse the archive" },
      { key: "wishlistAdd", label: "Wishlist: add-to-bag button", default: "Add" },
      { key: "wishlistAddAria", label: "Heart (add) — screen-reader label", default: "Add to wishlist" },
      { key: "wishlistRemoveAria", label: "Heart (remove) — screen-reader label", default: "Remove from wishlist" },
      { key: "recentlyViewedHeading", label: "Recently viewed heading", default: "Recently Viewed" },
    ],
  },
  {
    group: "Search & filters",
    fields: [
      { key: "filterSearchPlaceholder", label: "Filter box placeholder", default: "Search by title, author, category…" },
      { key: "filterClearAria", label: "Clear button — screen-reader label", default: "Clear search" },
      { key: "sort_newest", label: "Sort: newest", default: "Newest" },
      { key: "sort_price_asc", label: "Sort: price low→high", default: "Price ↑" },
      { key: "sort_price_desc", label: "Sort: price high→low", default: "Price ↓" },
      { key: "sort_title_az", label: "Sort: A→Z", default: "A → Z" },
      { key: "sort_title_za", label: "Sort: Z→A", default: "Z → A" },
      { key: "filterInStock", label: "In-stock toggle", default: "In stock" },
      { key: "filterResults", label: "Result count", default: "{count} results", hint: "Use {count} for the number of results." },
      { key: "searchDialogAria", label: "Search overlay — screen-reader label", default: "Search products" },
      { key: "searchPlaceholder", label: "Search overlay placeholder", default: "Search books, authors, categories…" },
      { key: "searchCloseAria", label: "Search close — screen-reader label", default: "Close search" },
      { key: "searchPrompt", label: "Search prompt", default: "Start typing to search" },
      { key: "searchNoResults", label: "No results", default: "No results for “{query}”", hint: "Use {query} for what was typed." },
    ],
  },
  {
    group: "Order tracking",
    fields: [
      { key: "trackEyebrow", label: "Eyebrow", default: "Order Ledger" },
      { key: "trackTitle", label: "Heading", default: "Track Order" },
      { key: "trackSubtitle", label: "Subheading", default: "Secure Order Status Ledger" },
      { key: "trackOrderLabel", label: "Order ID label", default: "ORDER IDENTIFIER" },
      { key: "trackOrderPlaceholder", label: "Order ID placeholder", default: "e.g. ABCD-123456" },
      { key: "trackEmailLabel", label: "Email label", default: "CUSTOMER EMAIL" },
      { key: "trackEmailPlaceholder", label: "Email placeholder", default: "e.g. reader@archive.com" },
      { key: "trackSubmit", label: "Submit button", default: "Initialize Pulse" },
      { key: "trackLoading", label: "Submit button (loading)", default: "Querying..." },
      { key: "trackFound", label: "Order found banner", default: "ARCHIVE MATCH FOUND" },
      { key: "trackTotalPayable", label: "Total payable label", default: "Total Payable" },
      { key: "trackBack", label: "Back link", default: "Back to Store" },
      { key: "trackTimeline", label: "Timeline heading", default: "Transit Status Timeline" },
      { key: "trackFulfillment", label: "Pickup or delivery details heading", default: "How to receive your order" },
      { key: "trackPickup", label: "Pickup method label", default: "Pick up" },
      { key: "trackLocalDelivery", label: "Local delivery method label", default: "Local delivery" },
      { key: "trackPickupReady", label: "Pickup ready status", default: "Ready for pickup" },
      { key: "trackCollected", label: "Pickup completed status", default: "Collected" },
      { key: "trackReadyForDelivery", label: "Local delivery prepared status", default: "Preparing your local delivery" },
      { key: "trackOutForDelivery", label: "Out for local delivery status", default: "Out for delivery" },
      { key: "trackFulfillmentEstimate", label: "Pickup or delivery estimate label", default: "Estimate" },
      { key: "trackFulfillmentInstructions", label: "Pickup or delivery instructions label", default: "Instructions" },
      { key: "trackFulfillmentHours", label: "Pickup hours label", default: "Hours" },
      { key: "trackLogisticsEyebrow", label: "Logistics eyebrow", default: "Fulfillment Logistics" },
      { key: "trackCarrier", label: "Carrier heading", default: "Carrier Assigned" },
      { key: "trackDigitalTitle", label: "Digital delivery heading", default: "Digital Archive Delivery" },
      { key: "trackDigitalText", label: "Digital delivery text", multiline: true, default: "Download your secure digital purchases below. Generated download tokens expire in 24 hours." },
      { key: "trackDigitalFormat", label: "Digital format line", default: "Format: Digital Book" },
      { key: "trackDownload", label: "Download button", default: "Download File" },
      { key: "trackItems", label: "Items heading", default: "Cart Items Ledger" },
      { key: "trackStepPaid", label: "Timeline step 1", default: "Paid" },
      { key: "trackStepPaidDesc", label: "Timeline step 1 — detail", default: "Order confirmed" },
      { key: "trackStepProcessing", label: "Timeline step 2", default: "Processing" },
      { key: "trackStepProcessingDesc", label: "Timeline step 2 — detail", default: "Packing items" },
      { key: "trackStepShipped", label: "Timeline step 3", default: "Shipped" },
      { key: "trackStepShippedDesc", label: "Timeline step 3 — detail", default: "In transit" },
      { key: "trackStepDelivered", label: "Timeline step 4", default: "Delivered" },
      { key: "trackStepDeliveredDesc", label: "Timeline step 4 — detail", default: "Arrival confirmed" },
      { key: "trackAnother", label: "Track-another button", default: "Track Another Order" },
      { key: "trackInTransit", label: "In-transit line", default: "Your parcel is in transit. Tracking number:" },
      { key: "trackShipment", label: "Carrier tracking button", default: "Track Shipment" },
      { key: "trackError", label: "Lookup error", default: "Failed to retrieve order tracking information." },
      { key: "trackErrFill", label: "Missing details error", default: "Please fill in both order ID and email." },
      { key: "trackErrNotFound", label: "Order not found error", default: "Order not found. Check the ID and try again." },
      { key: "trackErrEmail", label: "Email mismatch error", default: "Invalid credentials. Please verify your email." },
      { key: "trackCreated", label: "Created-date label", default: "Created:" },
      { key: "trackPaid", label: "Payment status: paid", default: "Paid" },
      { key: "trackUnpaid", label: "Payment status: unpaid", default: "Unpaid" },
      { key: "qtyLine", label: "Order item quantity", default: "QTY: {qty}", hint: "Use {qty} for the quantity." },
      { key: "summarySubtotal", label: "Summary: subtotal", default: "Subtotal" },
      { key: "summaryDiscount", label: "Summary: discount", default: "Discount" },
      { key: "summaryShipping", label: "Summary: shipping", default: "Shipping" },
      { key: "summaryTax", label: "Summary: tax", default: "Estimated Tax" },
      { key: "summaryTotal", label: "Summary: total", default: "Total" },
    ],
  },
  {
    group: "Customer account",
    fields: [
      { key: "accountTitle", label: "Sign-in / dashboard title", default: "Customer Account" },
      { key: "accountSubtitle", label: "Sign-in subtitle", default: "Lyricalmyrical Books Ledger" },
      { key: "accountSignInLabel", label: "Sign-in field label", default: "Passwordless Sign In" },
      { key: "accountEmailPlaceholder", label: "Email placeholder", default: "name@example.com" },
      { key: "accountMagicLink", label: "Magic-link button", default: "Send Magic Link" },
      { key: "accountOr", label: "Divider word", default: "OR" },
      { key: "accountGoogle", label: "Google button", default: "Continue with Google" },
      { key: "accountBackToStore", label: "Back link (signed out)", default: "Back to Storefront" },
      { key: "accountStorefront", label: "Back link (signed in)", default: "Storefront" },
      { key: "accountPortal", label: "Header label", default: "Vault Portal" },
      { key: "accountSignOut", label: "Sign-out button", default: "Sign out" },
      { key: "accountWishlist", label: "Tile: wishlist", default: "Wishlist Ledger" },
      { key: "accountSaved", label: "Tile: saved count", default: "{count} Saved", hint: "Use {count} for the number." },
      { key: "accountOrders", label: "Tile: orders", default: "Order Logs" },
      { key: "accountTransacted", label: "Tile: order count", default: "{count} Transacted" },
      { key: "accountShipping", label: "Tile: shipping", default: "Shipping Vector" },
      { key: "accountUnconfigured", label: "Tile: no address", default: "Unconfigured" },
      { key: "accountAddressTitle", label: "Address form heading", default: "Configure Shipping Vector" },
      { key: "accountAbort", label: "Address cancel", default: "ABORT" },
      { key: "accountCancel", label: "Address cancel button", default: "Cancel" },
      { key: "accountFieldName", label: "Field: name", default: "Full Legal Name" },
      { key: "accountFieldPhone", label: "Field: phone", default: "Contact Phone" },
      { key: "accountPhonePlaceholder", label: "Phone placeholder", default: "e.g. 647 123 4567" },
      { key: "accountFieldStreet", label: "Field: street", default: "Street Address" },
      { key: "accountStreetPlaceholder", label: "Street placeholder", default: "e.g. 456 Montrose Ave" },
      { key: "accountFieldCity", label: "Field: city", default: "City" },
      { key: "accountFieldState", label: "Field: state", default: "State / Province" },
      { key: "accountFieldZip", label: "Field: postal code", default: "Postal Code" },
      { key: "accountFieldCountry", label: "Field: country", default: "Country" },
      { key: "accountSaveAddress", label: "Save address button", default: "Save Vector Details" },
      { key: "accountHistory", label: "Order history heading", default: "Purchase History Log" },
      { key: "accountHistoryLoading", label: "Order history loading", default: "Accessing transaction logs..." },
      { key: "accountHistoryEmpty", label: "Order history empty", default: "No transaction entries found" },
      { key: "accountDigitalTitle", label: "Digital heading", default: "Digital Archive Access" },
      { key: "accountDigitalText", label: "Digital text", default: "Download your digital secure purchases. Tokens refresh automatically." },
      { key: "accountEbook", label: "E-book label", default: "E-Book File" },
      { key: "accountDownload", label: "Download button", default: "Download E-Book" },
      { key: "accountItems", label: "Items heading", default: "Items Breakdown" },
      { key: "accountDispatch", label: "Dispatch heading", default: "Dispatch Logistics" },
      { key: "accountShipTo", label: "Ship-to heading", default: "Shipping Address" },
      { key: "accountLogisticsFee", label: "Shipping fee label", default: "Logistics Fee" },
      { key: "accountManage", label: "Address tile: open", default: "MANAGE" },
      { key: "accountClose", label: "Address tile: close", default: "CLOSE" },
      { key: "accountDelivered", label: "Order status: delivered", default: "DELIVERED" },
      { key: "accountUnfulfilled", label: "Order status: not shipped yet", default: "UNFULFILLED" },
      { key: "accountShipped", label: "Order status: shipped", default: "SHIPPED" },
      { key: "accountProcessing", label: "Order status: processing", default: "PROCESSING" },
      { key: "accountPaid", label: "Payment status: paid", default: "PAID" },
      { key: "accountUnpaid", label: "Payment status: unpaid", default: "UNPAID" },
      { key: "accountRefunded", label: "Payment status: refunded", default: "REFUNDED" },
      { key: "accountPartiallyRefunded", label: "Payment status: partially refunded", default: "PARTIALLY REFUNDED" },
      { key: "accountTrackPackage", label: "Track package button", default: "Track Package" },
      { key: "accountSignInError", label: "Sign-in link error", default: "Failed to sign in. Link may be expired." },
      { key: "accountConfirmEmailPrompt", label: "Confirm email prompt (sign-in link opened on a new device)", default: "Please enter your email to confirm sign-in:" },
      { key: "accountMagicLinkError", label: "Magic-link send error", default: "Failed to send magic link." },
      { key: "accountGoogleError", label: "Google sign-in error", default: "Google Authentication failed." },
      { key: "accountSignedInLink", label: "Signed in via email link", default: "Successfully signed in with email link!" },
      { key: "accountLinkSent", label: "Magic link sent", default: "Magic sign-in link dispatched! Check your email." },
      { key: "accountSignedIn", label: "Signed in", default: "Successfully logged in!" },
      { key: "accountAddressSaved", label: "Address saved", default: "Profile address updated successfully!" },
      { key: "accountAddressError", label: "Address save error", default: "Failed to save address details." },
      { key: "accountDownloadError", label: "Download link error", default: "Download token has expired or is invalid." },
      { key: "accountBookCountOne", label: "Order row book count (1)", default: "{count} book", hint: "Use {count} for the number." },
      { key: "accountBookCountMany", label: "Order row book count (many)", default: "{count} books", hint: "Use {count} for the number." },
      { key: "carrierLabel", label: "Carrier label", default: "Carrier:" },
      { key: "trackingCodeLabel", label: "Tracking code label", default: "Code:" },
    ],
  },
  {
    group: "Checkout",
    fields: [
      { key: "coBrand", label: "Header brand name", default: "Lyricalmyrical Books" },
      { key: "coReturn", label: "Back link", default: "Return to store" },
      { key: "coSecure", label: "Secure label", default: "Secure checkout" },
      { key: "coProgressAria", label: "Progress — screen-reader label", default: "Checkout progress" },
      { key: "coStepInfo", label: "Breadcrumb: information", default: "Information" },
      { key: "coStepShipping", label: "Breadcrumb: shipping", default: "Shipping" },
      { key: "coStepPayment", label: "Breadcrumb: payment", default: "Payment" },
      { key: "coStepOf", label: "Step counter", default: "{n} of 3", hint: "Use {n} for the step number." },
      { key: "coContact", label: "Section: contact", default: "Contact" },
      { key: "coDelivery", label: "Section: delivery", default: "Delivery" },
      { key: "coPayment", label: "Section: payment", default: "Payment" },
      { key: "coSignedIn", label: "Signed-in label", default: "Signed in" },
      { key: "coGoogle", label: "Google sign-in button", default: "Sign in with Google" },
      { key: "coEmail", label: "Field: email", default: "Email address" },
      { key: "coEmailNote", label: "Email note", default: "We’ll send your receipt and delivery updates to this email." },
      { key: "coName", label: "Field: full name", default: "Full name" },
      { key: "coAddress", label: "Field: address", default: "Address" },
      { key: "coCountry", label: "Field: country", default: "Country" },
      { key: "coCity", label: "Field: city", default: "City" },
      { key: "coState", label: "Field: state", default: "State / province" },
      { key: "coZip", label: "Field: postal code", default: "ZIP / postal code" },
      { key: "coPhone", label: "Field: phone", default: "Phone (optional)" },
      { key: "coShipMethod", label: "Fulfillment-choice heading", default: "How would you like to receive your order?" },
      { key: "coShipMethodNote", label: "Fulfillment-choice note", default: "Choose shipping, pickup, or a local delivery option when available." },
      { key: "coFulfillmentGroup", label: "Fulfillment choices — screen-reader group", default: "How would you like to receive your order?" },
      { key: "coFulfillmentShipping", label: "Ship to address choice", default: "Ship to address" },
      { key: "coFulfillmentPickup", label: "Pickup choice", default: "Pick up in person" },
      { key: "coFulfillmentDelivery", label: "Local delivery choice", default: "Local delivery" },
      { key: "coFulfillmentReview", label: "Choose a fulfillment option notice", default: "Choose an available option to continue." },
      { key: "coFulfillmentUnavailable", label: "No matching fulfillment option", default: "No option is available for this order and address." },
      { key: "coFulfillmentAddressPrompt", label: "Local delivery address prompt", default: "Enter a complete Canadian postal address in an eligible delivery area." },
      { key: "coFulfillmentInstructions", label: "Pickup or delivery instructions label", default: "Instructions:" },
      { key: "coFulfillmentHours", label: "Pickup hours label", default: "Hours:" },
      { key: "coFulfillmentEstimate", label: "Pickup or delivery estimate label", default: "Estimate:" },
      { key: "coBillingTitle", label: "Pickup billing address heading", default: "Billing location for tax" },
      { key: "coBillingNote", label: "Pickup billing address explanation", default: "Enter your billing country and province or state to calculate tax." },
      { key: "coBillCountry", label: "Pickup billing country label", default: "Billing country" },
      { key: "coBillState", label: "Pickup billing state label", default: "Billing state / province" },
      { key: "coBillStateChoose", label: "Pickup billing province placeholder", default: "Choose…" },
      { key: "coFulfillmentTaxLocation", label: "Pickup tax location label", default: "Pickup location tax applies to collected books." },
      { key: "coManualOrderError", label: "Local manual-order error", default: "We couldn’t place this order. Review your items and fulfillment choice, then try again.", multiline: true },
      { key: "coOrderNote", label: "Order note: label", default: "Order note or gift message (optional)" },
      { key: "coOrderNoteHelp", label: "Order note: help text", default: "Tell us anything we should know about this order. Up to 500 characters." },
      { key: "coRates", label: "Loading rates text", default: "Calculating live shipping rates..." },
      { key: "coPaymentNote", label: "Payment note", default: "All transactions are handled by the payment provider you select." },
      { key: "coCard", label: "Card option", default: "Credit or debit card" },
      { key: "coCardsAria", label: "Accepted cards — screen-reader label", default: "Accepted cards" },
      { key: "coPay", label: "Pay button (card)", default: "Pay securely" },
      { key: "coPayWithTotal", label: "Pay button with total (card)", default: "Pay {total} securely", hint: "Use {total} for the order total." },
      { key: "coHaveCode", label: "Discount code link", default: "Have a discount code?" },
      { key: "coArrivesBy", label: "Delivery arrival date", default: "Arrives by {date}", hint: "Use {date} for the latest expected day." },
      { key: "coFreeShipGap", label: "Free-shipping nudge", default: "Add {amount} more for free shipping", hint: "Use {amount} for what's still needed." },
      { key: "coOnlyLeft", label: "Low-stock line in order summary", default: "Only {count} left" },
      { key: "coGuarantee", label: "Promise under Pay button (e.g. returns)", default: "", hint: "Leave blank to hide. Only promise what your policy really offers." },
      { key: "coPayPal", label: "Pay button (PayPal)", default: "Continue to PayPal" },
      { key: "coPlaceOrder", label: "Pay button (manual)", default: "Place order" },
      { key: "coProcessing", label: "Pay button (processing)", default: "Processing order…" },
      { key: "coTrust1", label: "Trust badge 1", default: "Secure payment" },
      { key: "coTrust2", label: "Trust badge 2", default: "Order support" },
      { key: "coTrust3", label: "Trust badge 3", default: "Privacy protected" },
      { key: "coSummary", label: "Order-summary heading", default: "Order summary" },
      { key: "coDiscount", label: "Discount placeholder", default: "Discount code" },
      { key: "coDiscountRemove", label: "Remove discount — screen-reader label", default: "Remove discount" },
      { key: "coTaxLater", label: "Tax placeholder", default: "Calculated at checkout" },
      { key: "coPacked", label: "Reassurance title", default: "Carefully packed and tracked" },
      { key: "coPickup", label: "Pickup note", default: "Collect in person — no delivery" },
      { key: "coCarrierTransit", label: "Carrier transit estimate", default: "Estimated {days} business days after dispatch", hint: "Use {days} for the carrier transit estimate for this address and service." },
      { key: "coCarrierTimingUnavailable", label: "Carrier timing unavailable", default: "Carrier delivery estimate unavailable" },
      { key: "coEstimated", label: "Delivery estimate", default: "Estimated {days} business days", hint: "Use {days} for the number of days." },
      { key: "coFree", label: "Free shipping label", default: "Free" },
      { key: "coNoPayment", label: "No payment method message", multiline: true, default: "No payment method is currently available. Please contact the store before placing your order." },
      { key: "coStripeConfigError", label: "Card payment configuration error", multiline: true, default: "Card payments are temporarily unavailable. Please contact the store or choose another payment method." },
      { key: "coPrivacyNote", label: "Payment privacy note", multiline: true, default: "Your payment details are submitted directly to the selected payment provider and are not stored by this shop." },
      { key: "coPackedNote", label: "Reassurance text", default: "You’ll receive an order confirmation and shipping updates by email." },
      { key: "coTestMode", label: "Test-mode banner", default: "Test mode is active. No real charges will be made." },
      { key: "coThanks", label: "Thank-you heading", default: "Thank You" },
      { key: "coPending", label: "Pending-payment message", default: "Your order is pending verification of payment. We will ship once received." },
      { key: "coContinue", label: "Thank-you button", default: "Continue Exploring" },
      { key: "coEmptyEyebrow", label: "Empty cart eyebrow", default: "Empty Archive" },
      { key: "coEmptyTitle", label: "Empty cart heading", default: "Nothing Here" },
      { key: "coEmptyButton", label: "Empty cart button", default: "Return to Catalog" },
      { key: "coOrderPlaced", label: "Thank-you status: placed (manual payment)", default: "Order Placed" },
      { key: "coOrderConfirmed", label: "Thank-you status: confirmed", default: "Order Confirmed" },
      { key: "coFinalizing", label: "Thank-you status: finalizing", default: "Finalizing Payment" },
      { key: "coPaymentInstructions", label: "Manual payment heading", default: "Payment Instructions" },
      { key: "coCheckEmail", label: "Manual payment fallback text", default: "Please check your email for payment instructions." },
      { key: "coEnterAddress", label: "Shipping methods placeholder", default: "Enter your delivery address to see available shipping methods." },
      { key: "coCardBrands", label: "Card brand badges (comma-separated)", default: "VISA, MC, AMEX, Apple Pay", hint: "Write Apple Pay to show the Apple Pay mark." },
      { key: "coStripeRetry", label: "Inline Stripe form retry button", default: "Reload payment form" },
      { key: "coStripeRetryNote", label: "Inline Stripe form retry explanation", multiline: true, default: "Reload the secure payment fields here. Your bag and delivery details stay saved." },
      { key: "coStripeNote", label: "Card redirect note", default: "After you click “Pay securely,” you’ll complete your card payment on Stripe’s secure checkout." },
      { key: "coAddressSuggestions", label: "Address suggestions list (screen readers)", default: "Address suggestions" },
      { key: "coAddressAttribution", label: "Address suggestions credit line", default: "Suggestions © OpenStreetMap contributors" },
      { key: "coCountrySearch", label: "Country picker — search hint", default: "Start typing your country…" },
      { key: "coCountryPopular", label: "Country picker — top group heading", default: "Popular" },
      { key: "coCountryAll", label: "Country picker — full list heading", default: "All countries" },
      { key: "coCountryNone", label: "Country picker — no match", default: "No country matches “{query}”", hint: "Use {query} for what was typed." },
      { key: "coShowSummary", label: "Phone summary bar — closed", default: "Show order summary" },
      { key: "coHideSummary", label: "Phone summary bar — open", default: "Hide order summary" },
      { key: "coStateChoose", label: "State / province drop-down placeholder", default: "Choose…" },
      { key: "coStripeLoading", label: "Card form loading", default: "Loading secure card form…" },
      { key: "coStripeLoadError", label: "Card form failed to load", default: "The card form couldn’t load. Refresh the page or try again." },
      { key: "coPaymentNotFinished", label: "Returned without paying", default: "Your payment wasn’t completed. Your details are saved — click “Pay securely” to try again." },
      { key: "coDiscountInvalid", label: "Discount error (no longer valid)", default: "Discount no longer valid." },
      { key: "coDiscountExpired", label: "Discount error (invalid code)", default: "INVALID OR EXPIRED CODE" },
      { key: "coPaypalError", label: "PayPal start error", default: "Failed to create PayPal order." },
      { key: "coStripeError", label: "Card checkout start error", default: "Failed to create secure Stripe session." },
      { key: "coPaypalCaptureError", label: "PayPal capture error", default: "PayPal capture failed." },
      { key: "coOrderNumber", label: "Thank-you order number", default: "ORDER #{number}", hint: "Use {number} for the order number." },
      { key: "coConfirmationSent", label: "Thank-you note (paid)", default: "A confirmation will be sent to your email." },
      { key: "coConfirming", label: "Thank-you note (confirming)", default: "Your payment is being confirmed — the receipt email will follow shortly." },
      { key: "coNoShipping", label: "No shipping to country", default: "We don't currently offer shipping for this order to {country}. Try another country or contact us for a custom quote.", hint: "Use {country} for the country." },
      { key: "coItemCountOne", label: "Summary item count (1)", default: "{count} item", hint: "Use {count} for the number." },
      { key: "coItemCountMany", label: "Summary item count (many)", default: "{count} items", hint: "Use {count} for the number." },
      { key: "coApply", label: "Discount apply button", default: "Apply" },
      { key: "coDiscountApplied", label: "Discount applied message", default: "{code} applied", hint: "Use {code} for the code." },
      { key: "coErrMinItems", label: "Discount error — minimum items", default: "This code requires a minimum of {count} items in your cart.", hint: "Use {count} for the number of items." },
      { key: "coErrMinOrder", label: "Discount error — minimum order", default: "This code requires a minimum order of {amount}.", hint: "Use {amount} for the amount." },
      { key: "coErrNeedEmail", label: "Discount error — email needed first", default: "Please enter your email address under 'Shipping Details' first to apply this code." },
      { key: "coErrVipEmails", label: "Discount error — VIP emails only", default: "This code is restricted to specific VIP customer emails." },
      { key: "coErrEmailDomains", label: "Discount error — email domains", default: "This code is restricted to specific email domains (e.g. {domains}).", hint: "Use {domains} for the allowed domains." },
      { key: "coErrCategories", label: "Discount error — categories only", default: "This code only applies to categories: {categories}.", hint: "Use {categories} for the category list." },
      { key: "coErrProducts", label: "Discount error — specific products only", default: "This code only applies to specific products not currently in your cart." },
      { key: "coErrBogo", label: "Discount error — buy-N-get-one", default: "This BOGO code requires buying at least {count} qualifying items.", hint: "Use {count} for the number of items." },
      { key: "coErrTiered", label: "Discount error — tiered code misconfigured", default: "This tiered code is not configured correctly." },
      { key: "coErrMinSpend", label: "Discount error — minimum spend", default: "This code requires a minimum spend of {amount} on qualifying items.", hint: "Use {amount} for the amount." },
      { key: "coErrShippingFields", label: "Missing shipping details message", default: "Please fill in all required shipping details, including city, state/province, and postal/zip code.", multiline: true },
      { key: "coErrPickupBillingFields", label: "Missing billing location for pickup taxes", default: "Enter your billing country and province or state so we can calculate pickup taxes.", multiline: true },
      { key: "coErrAddressService", label: "Address verification unreachable", default: "Could not connect to address verification service." },
      { key: "coErrPaypalUrl", label: "PayPal — no approval link", default: "PayPal did not return an approval URL." },
      { key: "coErrPaypalToken", label: "PayPal — no order token", default: "PayPal did not return an order token." },
      { key: "coErrNoCheckoutUrl", label: "Payment server — no checkout link", default: "No checkout URL returned from payment server." },
      { key: "coCheckoutFailed", label: "Checkout failed message", default: "We couldn’t complete checkout: {error}. Check your order status before retrying.", hint: "Use {error} for the editable reason.", multiline: true },
      { key: "coCardValidationError", label: "Card details validation message", default: "Please check the highlighted payment details." },
      { key: "coCardPaymentError", label: "Card payment error", default: "We couldn’t confirm your payment. Check your order status before retrying or choose another payment method.", multiline: true },
      { key: "coPaymentCanceled", label: "Payment canceled message", default: "Payment was canceled. Your cart is saved — you can review it and try again.", multiline: true },
    ],
  },
  {
    group: "Sections",
    fields: [
      { key: "sectionNoImage", label: "Empty image placeholder", default: "No Image" },
      { key: "sectionNoVideo", label: "Empty video placeholder", default: "No Video" },
      { key: "sectionGoToCover", label: "Cover carousel dot — screen-reader label", default: "Go to cover {n}", hint: "Use {n} for the cover number." },
      { key: "sectionViewBook", label: "Book link — screen-reader label", default: "View {title}", hint: "Use {title} for the book title." },
      { key: "sectionQuickAddAria", label: "Quick-add button — screen-reader label", default: "Add {title} to bag", hint: "Use {title} for the book title." },
      { key: "sectionSoldOutAria", label: "Quick-add button (sold out) — screen-reader label", default: "{title} is sold out", hint: "Use {title} for the book title." },
    ],
  },
  {
    group: "Reviews",
    fields: [
      { key: "reviewsHeading", label: "Section heading", default: "Customer Reviews" },
      { key: "reviewsNone", label: "No reviews (summary)", default: "No reviews yet" },
      { key: "reviewsCountOne", label: "Count (1 review)", default: "{count} review", hint: "Use {count} for the number." },
      { key: "reviewsCountMany", label: "Count (many reviews)", default: "{count} reviews", hint: "Use {count} for the number." },
      { key: "reviewsLoading", label: "Loading text", default: "Loading reviews…" },
      { key: "reviewsEmpty", label: "Empty message", default: "Be the first to share your thoughts on this book." },
      { key: "reviewsAuthor", label: "Review author credit", default: "— {author}", hint: "Use {author} for the reviewer name." },
      { key: "reviewsReply", label: "Store reply label", default: "Reply from Lyricalmyrical Books" },
      { key: "reviewsThanks", label: "Submitted message", default: "Thanks — your review has been submitted for moderation." },
      { key: "reviewsWrite", label: "Form heading", default: "Write a review" },
      { key: "reviewsRating", label: "Rating label", default: "Your rating" },
      { key: "reviewsName", label: "Name placeholder", default: "Name" },
      { key: "reviewsEmail", label: "Email placeholder", default: "Email (optional, not published)" },
      { key: "reviewsHeadline", label: "Headline placeholder", default: "Headline (optional)" },
      { key: "reviewsBody", label: "Body placeholder", default: "What did you think?" },
      { key: "reviewsSubmit", label: "Submit button", default: "Submit Review" },
      { key: "reviewsModerated", label: "Moderation note", default: "Reviews are moderated before appearing." },
      { key: "reviewsError", label: "Submit error", default: "Could not submit review." },
      { key: "reviewsErrRequired", label: "Missing name/review error", default: "Name and review body are required." },
      { key: "reviewsStarOne", label: "Star rating — screen-reader label (1)", default: "{n} star", hint: "Use {n} for the rating." },
      { key: "reviewsStarMany", label: "Star rating — screen-reader label (many)", default: "{n} stars", hint: "Use {n} for the rating." },
    ],
  },
];

/**
 * Legacy flat keys that are edited elsewhere in the theme editor (Text & Translations › System Labels,
 * Products › Badges). They keep a default here but are intentionally not listed in COPY_SCHEMA, so
 * the Content panel never shows two inputs for one string.
 */
export const FLAT_COPY_DEFAULTS: Record<string, string> = {
  cartLabel: "Bag",
  soldOutLabel: "Sold Out",
  saleBadgeLabel: "Sale",
};

// Flat key → default lookup, derived once from the schema.
export const DEFAULT_COPY: Record<string, string> = COPY_SCHEMA.reduce(
  (acc, g) => {
    for (const f of g.fields) acc[f.key] = f.default;
    return acc;
  },
  { ...FLAT_COPY_DEFAULTS } as Record<string, string>,
);

/** Unexpanded copy for authoring: editing a default must retain {year}/{name} tokens. */
export function getCopyTemplate(design: any, key: string): string {
  const override = design?.copy?.[key];
  if (typeof override === "string") return override;
  const legacy = design?.[key];
  return (typeof legacy === "string" && legacy ? legacy : DEFAULT_COPY[key]) || "";
}

/**
 * Resolve a shopper-facing string. Order of precedence:
 *   design.copy[key]  →  design[key] (legacy flat)  →  schema default.
 * Supports {year} token replacement and optional extra vars.
 */
export function getCopy(design: any, key: string, vars?: Record<string, string | number>): string {
  const raw = getCopyTemplate(design, key);
  const all: Record<string, string | number> = { year: new Date().getFullYear(), ...(vars || {}) };
  // {name} is the site name (Text & labels › Site & sharing) in every string that mentions it.
  if (!("name" in all) && key !== "siteName" && raw.includes("{name}")) all.name = getCopy(design, "siteName");
  return raw.replace(/\{(\w+)\}/g, (m: string, name: string) =>
    name in all ? String(all[name]) : m,
  );
}

/** Local validation reasons stay editable; provider diagnostics never become shopper copy. */
export class CopyError extends Error {
  constructor(design: any, public key: string, public vars?: Record<string, string | number>) {
    super(getCopy(design, key, vars));
  }
}
export function copyErrorText(error: unknown, design: any, fallback: string): string {
  return error instanceof CopyError ? getCopy(design, error.key, error.vars) : getCopy(design, fallback);
}
