// Fallback wording for section renderers, keyed "<SectionType>.<field>".
// A section's own Content fields always win; these only fill in fields that were never set.
// (Clearing a settings-level field on purpose leaves it blank — see SectionComponents.)
// admin/sectionFallbacks.test.ts checks that every settings-level key has a Content field.
export const SECTION_FALLBACKS: Record<string, string> = {
  "CompositionSection.block.text": "Button",
  "HeroSection.title": "Lyricalmyrical",
  "HeroSection.subtitle": "Photography & Art Books",
  "HeroSection.ctaText": "Explore",
  "ImageBannerSection.title": "Stories worth keeping",
  "FeatureGridSection.title": "Highlights",
  "NewsletterSection.title": "Join the Archive",
  "NewsletterSection.description": "Occasional dispatches about new publications and limited editions.",
  "NewsletterSection.placeholder": "email@example.com",
  "NewsletterSection.buttonLabel": "JOIN",
  "TestimonialsSection.title": "Testimonials",
  "FAQSection.title": "FAQ",
  "ImageWithTextSection.title": "About the collection",
  "ImageWithTextSection.body": "Pair text with an image to give focus to your chosen product or collection.",
  "MarqueeSection.text": "Free shipping over $100 · New arrivals weekly · Independent & original",
  "MulticolumnSection.item.title": "Column",
  "SlideshowSection.prevAria": "Previous slide",
  "SlideshowSection.nextAria": "Next slide",
  "SlideshowSection.dotAria": "Go to slide {n}",
  "VideoSection.title": "Video",
  "LogoListSection.item.alt": "Logo",
  "CollapsibleSection.item.heading": "Heading",
  "CollectionListSection.item.title": "Collection",
  "FeaturedProductSection.eyebrow": "Featured",
  "FeaturedProductSection.ctaText": "View product",
  "ProductGridHeaderSection.title": "Lyricalmyrical Books",
  "ProductGridHeaderSection.cartLabel": "Cart",
  "ProductGridHeaderSection.cartTotalText": "CA$130.00",
  "ProductGridHeaderSection.navText": "Products · About · Project Submissions · Contact",
  "ProductGridHeaderSection.saleLabel": "On sale",
  "ProductCoverCarouselSection.title": "Lyricalmyrical Books",
  "StaffNotesTableSection.colTitleLabel": "TITLE",
  "StaffNotesTableSection.colCategoryLabel": "CATEGORY",
  "StaffNotesTableSection.colFormatLabel": "FORMAT",
  "StaffNotesTableSection.colNoteLabel": "NOTE",
  "BlogPostsSection.article.title": "Article image",
  "BlogPostsSection.article.title@1797": "Untitled article",
  "BlogPostsSection.ctaText": "Read more",
  "CountdownSection.title": "Limited time offer",
  "CountdownSection.labelDays": "Days",
  "CountdownSection.labelHours": "Hours",
  "CountdownSection.labelMinutes": "Min",
  "CountdownSection.labelSeconds": "Sec",
  "ContactFormSection.title": "Get in touch",
  "ContactFormSection.successMessage": "Thanks — we'll be in touch.",
  "ContactFormSection.namePlaceholder": "Name",
  "ContactFormSection.emailPlaceholder": "Email",
  "ContactFormSection.phonePlaceholder": "Phone",
  "ContactFormSection.messagePlaceholder": "Message",
  "ContactFormSection.buttonLabel": "Send message",
  "ContactFormSection.subjectPlaceholder": "Subject",
  "ContactFormSection.sendingLabel": "Sending…",
  "ContactFormSection.errorMessage": "Sorry — your message couldn't be sent. Please try again.",
  "MapSection.address": "New York, NY",
  "MapSection.title": "Map",
  "MapSection.btn.text": "Shop now",
  "MapSection.block.buttonText": "Shop now",
  "MapSection.block.title": "Video",
  "VideoHeroSection.headline": "Background video",
  "PricingTableSection.highlightLabel": "Most popular",
  "PageContentSection.page.title": "Page title",
};

export const fb = (key: string): string => SECTION_FALLBACKS[key] ?? "";
